/* Generated by re2c 0.14.3 on Wed Dec  9 09:57:06 2015 */
#line 1 "Lexer_re2c.cpp"
#include <Lexer.h>
#include <iostream>

#define TOKEN(type)                                                       \
this->token(tokType::type, tokStart, yycursor - tokStart, lineno, column);\
lastType = tokType::type;                                                 \
continue

namespace ppc {

bool Lexer::tokenize() {
    const char *yymarker,
            *yycursor = this->code.c_str(),
            *yyctxmarker = yycursor,
            *tokStart = yycursor;
    int column = 1, lineno = 1;
    enum tokType lastType = tokType::NOTHING;
    for (; ;) {
        if (lastType != tokType::NOTHING) {
            column += yycursor - tokStart;
        }

        tokStart = yycursor;

        if (lastType == tokType::STRING_CONST ||
            lastType == tokType::WSTRING_CONST ||
            lastType == tokType::HERE_STRING_CONST ||
            lastType == tokType::HERE_WSTRING_CONST) {
            for (auto c : this->tokens.back()->value) {
                if (c == '\n') {
                    lineno++;
                    column = 1;
                }
            }
        }
        
#line 40 "LexerTokenizer.cpp"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm[] = {
		/* table 1 .. 8: 0 */
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,  64, 128, 128, 160, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		159, 159, 151, 151, 151, 151, 151, 151, 
		147, 147, 128, 128, 128, 128, 128, 128, 
		128, 145, 145, 145, 145, 145, 145, 144, 
		144, 144, 144, 144, 144, 144, 144, 144, 
		144, 144, 144, 144, 144, 144, 144, 144, 
		144, 144, 144, 128, 128, 128, 128, 144, 
		128, 145, 145, 145, 145, 145, 145, 144, 
		144, 144, 144, 144, 144, 144, 144, 144, 
		144, 144, 144, 144, 144, 144, 144, 144, 
		144, 144, 144, 128, 128, 128, 128, 128, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		/* table 9 .. 10: 256 */
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 128, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192,   0, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192,   0, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		192, 192, 192, 192, 192, 192, 192, 192, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};

	yych = *yycursor;
	if (yych <= ']') {
		if (yych <= ',') {
			if (yych <= '"') {
				if (yych <= '\f') {
					if (yych <= 0x00) goto yy5;
					if (yych == '\n') goto yy9;
					goto yy89;
				} else {
					if (yych <= 0x1F) {
						if (yych <= '\r') goto yy11;
						goto yy89;
					} else {
						if (yych <= ' ') goto yy7;
						if (yych <= '!') goto yy89;
						goto yy88;
					}
				}
			} else {
				if (yych <= '\'') {
					if (yych <= '$') {
						if (yych <= '#') goto yy3;
						goto yy89;
					} else {
						if (yych <= '%') goto yy24;
						if (yych <= '&') goto yy38;
						goto yy86;
					}
				} else {
					if (yych <= ')') {
						if (yych <= '(') goto yy52;
						goto yy54;
					} else {
						if (yych <= '*') goto yy30;
						if (yych <= '+') goto yy26;
						goto yy48;
					}
				}
			}
		} else {
			if (yych <= '>') {
				if (yych <= '9') {
					if (yych <= '.') {
						if (yych <= '-') goto yy28;
						goto yy46;
					} else {
						if (yych <= '/') goto yy32;
						if (yych <= '0') goto yy83;
						goto yy85;
					}
				} else {
					if (yych <= ';') {
						if (yych <= ':') goto yy44;
						goto yy89;
					} else {
						if (yych <= '<') goto yy22;
						if (yych <= '=') goto yy40;
						goto yy20;
					}
				}
			} else {
				if (yych <= 'M') {
					if (yych <= '@') {
						if (yych <= '?') goto yy42;
						goto yy64;
					} else {
						if (yych == 'L') goto yy82;
						goto yy81;
					}
				} else {
					if (yych <= 'Z') {
						if (yych <= 'N') goto yy79;
						goto yy81;
					} else {
						if (yych <= '[') goto yy56;
						if (yych <= '\\') goto yy89;
						goto yy58;
					}
				}
			}
		}
	} else {
		if (yych <= 'q') {
			if (yych <= 'g') {
				if (yych <= 'b') {
					if (yych <= '_') {
						if (yych <= '^') goto yy34;
						goto yy80;
					} else {
						if (yych <= '`') goto yy89;
						if (yych <= 'a') goto yy18;
						goto yy78;
					}
				} else {
					if (yych <= 'd') {
						if (yych <= 'c') goto yy67;
						goto yy73;
					} else {
						if (yych <= 'e') goto yy75;
						if (yych <= 'f') goto yy15;
						goto yy77;
					}
				}
			} else {
				if (yych <= 'l') {
					if (yych <= 'i') {
						if (yych <= 'h') goto yy81;
						goto yy16;
					} else {
						if (yych <= 'j') goto yy71;
						if (yych <= 'k') goto yy81;
						goto yy70;
					}
				} else {
					if (yych <= 'n') {
						if (yych <= 'm') goto yy81;
						goto yy17;
					} else {
						if (yych <= 'o') goto yy19;
						if (yych <= 'p') goto yy72;
						goto yy81;
					}
				}
			}
		} else {
			if (yych <= '}') {
				if (yych <= 'v') {
					if (yych <= 's') {
						if (yych <= 'r') goto yy76;
						goto yy68;
					} else {
						if (yych <= 't') goto yy13;
						if (yych <= 'u') goto yy69;
						goto yy66;
					}
				} else {
					if (yych <= 'z') {
						if (yych <= 'w') goto yy74;
						goto yy81;
					} else {
						if (yych <= '{') goto yy60;
						if (yych <= '|') goto yy36;
						goto yy62;
					}
				}
			} else {
				if (yych <= 0xE0) {
					if (yych <= 0x7F) {
						if (yych <= '~') goto yy50;
						goto yy89;
					} else {
						if (yych <= 0xC1) goto yy2;
						if (yych <= 0xDF) goto yy90;
						goto yy91;
					}
				} else {
					if (yych <= 0xF0) {
						if (yych <= 0xEF) goto yy92;
						goto yy93;
					} else {
						if (yych <= 0xF3) goto yy94;
						if (yych <= 0xF4) goto yy95;
					}
				}
			}
		}
	}
yy2:
	yycursor = yymarker;
	if (yyaccept <= 4) {
		if (yyaccept <= 2) {
			if (yyaccept <= 1) {
				if (yyaccept == 0) {
					goto yy4;
				} else {
					goto yy47;
				}
			} else {
				goto yy65;
			}
		} else {
			if (yyaccept == 3) {
				goto yy14;
			} else {
				goto yy84;
			}
		}
	} else {
		if (yyaccept <= 7) {
			if (yyaccept <= 6) {
				if (yyaccept == 5) {
					goto yy87;
				} else {
					goto yy162;
				}
			} else {
				goto yy182;
			}
		} else {
			if (yyaccept == 8) {
				goto yy215;
			} else {
				goto yy659;
			}
		}
	}
yy3:
	yyaccept = 0;
	yych = *(yymarker = ++yycursor);
	goto yy864;
yy4:
#line 43 "Lexer_re2c.cpp"
	{continue;}
#line 326 "LexerTokenizer.cpp"
yy5:
	++yycursor;
#line 45 "Lexer_re2c.cpp"
	{return true;}
#line 331 "LexerTokenizer.cpp"
yy7:
	++yycursor;
#line 47 "Lexer_re2c.cpp"
	{
                if (!this->tokens.empty()) {
                    this->tokens.back()->spaced = true;
                }
                lastType = tokType::NOTHING;
                column++;
                continue;
            }
#line 343 "LexerTokenizer.cpp"
yy9:
	++yycursor;
	yych = *yycursor;
	goto yy862;
yy10:
#line 56 "Lexer_re2c.cpp"
	{
                if (!this->tokens.empty()) {
                    this->tokens.back()->newLine = true;
                }
                lastType = tokType::NOTHING;
                lineno += yycursor - tokStart;
                column = 1;
                continue;
            }
#line 359 "LexerTokenizer.cpp"
yy11:
	++yycursor;
	yych = *yycursor;
	goto yy860;
yy12:
#line 66 "Lexer_re2c.cpp"
	{
                lastType = tokType::NOTHING;
                continue;
            }
#line 370 "LexerTokenizer.cpp"
yy13:
	++yycursor;
	switch ((yych = *yycursor)) {
	case 'h':	goto yy831;
	case 'o':	goto yy832;
	case 'r':	goto yy834;
	case 'y':	goto yy835;
	default:	goto yy236;
	}
yy14:
#line 249 "Lexer_re2c.cpp"
	{TOKEN(IDENTIFIER);}
#line 383 "LexerTokenizer.cpp"
yy15:
	yych = *++yycursor;
	switch (yych) {
	case 'a':	goto yy814;
	case 'l':	goto yy815;
	case 'o':	goto yy816;
	case 'r':	goto yy817;
	default:	goto yy236;
	}
yy16:
	yych = *++yycursor;
	if (yych <= '8') {
		if (yych <= '3') {
			if (yych == '1') goto yy769;
			if (yych <= '2') goto yy236;
			goto yy770;
		} else {
			if (yych == '6') goto yy771;
			if (yych <= '7') goto yy236;
			goto yy772;
		}
	} else {
		if (yych <= 'm') {
			if (yych == 'f') goto yy774;
			if (yych <= 'l') goto yy236;
			goto yy776;
		} else {
			if (yych <= 'n') goto yy777;
			if (yych == 's') goto yy779;
			goto yy236;
		}
	}
yy17:
	yych = *++yycursor;
	if (yych == 'o') goto yy759;
	goto yy236;
yy18:
	yych = *++yycursor;
	if (yych <= 'm') {
		if (yych == 'l') goto yy740;
		goto yy236;
	} else {
		if (yych <= 'n') goto yy741;
		if (yych == 't') goto yy742;
		goto yy236;
	}
yy19:
	yych = *++yycursor;
	if (yych <= 'm') {
		if (yych == 'f') goto yy717;
		goto yy236;
	} else {
		if (yych <= 'n') goto yy718;
		if (yych == 'r') goto yy719;
		goto yy236;
	}
yy20:
	++yycursor;
	if ((yych = *yycursor) <= '<') goto yy21;
	if (yych <= '=') goto yy713;
	if (yych <= '>') goto yy711;
yy21:
#line 81 "Lexer_re2c.cpp"
	{TOKEN(GT);}
#line 448 "LexerTokenizer.cpp"
yy22:
	++yycursor;
	if ((yych = *yycursor) <= ';') goto yy23;
	if (yych <= '<') goto yy705;
	if (yych <= '=') goto yy707;
yy23:
#line 82 "Lexer_re2c.cpp"
	{TOKEN(LT);}
#line 457 "LexerTokenizer.cpp"
yy24:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy703;
#line 86 "Lexer_re2c.cpp"
	{TOKEN(MOD);}
#line 463 "LexerTokenizer.cpp"
yy26:
	++yycursor;
	if ((yych = *yycursor) == '+') goto yy701;
	if (yych == '=') goto yy699;
#line 87 "Lexer_re2c.cpp"
	{TOKEN(PLUS);}
#line 470 "LexerTokenizer.cpp"
yy28:
	++yycursor;
	if ((yych = *yycursor) <= '<') {
		if (yych == '-') goto yy697;
	} else {
		if (yych <= '=') goto yy695;
		if (yych <= '>') goto yy693;
	}
#line 88 "Lexer_re2c.cpp"
	{TOKEN(MINUS);}
#line 481 "LexerTokenizer.cpp"
yy30:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy691;
#line 89 "Lexer_re2c.cpp"
	{TOKEN(TIMES);}
#line 487 "LexerTokenizer.cpp"
yy32:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy689;
#line 90 "Lexer_re2c.cpp"
	{TOKEN(DIVIDE);}
#line 493 "LexerTokenizer.cpp"
yy34:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy687;
#line 93 "Lexer_re2c.cpp"
	{TOKEN(BITWISE_XOR);}
#line 499 "LexerTokenizer.cpp"
yy36:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy685;
#line 94 "Lexer_re2c.cpp"
	{TOKEN(BITWISE_OR);}
#line 505 "LexerTokenizer.cpp"
yy38:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy683;
#line 95 "Lexer_re2c.cpp"
	{TOKEN(BITWISE_AND);}
#line 511 "LexerTokenizer.cpp"
yy40:
	++yycursor;
#line 100 "Lexer_re2c.cpp"
	{TOKEN(EQUALS);}
#line 516 "LexerTokenizer.cpp"
yy42:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy681;
#line 118 "Lexer_re2c.cpp"
	{TOKEN(QUERY);}
#line 522 "LexerTokenizer.cpp"
yy44:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy679;
#line 116 "Lexer_re2c.cpp"
	{TOKEN(COLON);}
#line 528 "LexerTokenizer.cpp"
yy46:
	yyaccept = 1;
	yych = *(yymarker = ++yycursor);
	if (yych == '.') goto yy676;
	if (yych <= '/') goto yy47;
	if (yych <= '9') goto yy160;
yy47:
#line 115 "Lexer_re2c.cpp"
	{TOKEN(PERIOD);}
#line 538 "LexerTokenizer.cpp"
yy48:
	++yycursor;
#line 117 "Lexer_re2c.cpp"
	{TOKEN(COMMA);}
#line 543 "LexerTokenizer.cpp"
yy50:
	++yycursor;
#line 121 "Lexer_re2c.cpp"
	{TOKEN(BITWISE_NOT);}
#line 548 "LexerTokenizer.cpp"
yy52:
	++yycursor;
#line 122 "Lexer_re2c.cpp"
	{TOKEN(L_PAREN);}
#line 553 "LexerTokenizer.cpp"
yy54:
	++yycursor;
#line 123 "Lexer_re2c.cpp"
	{TOKEN(R_PAREN);}
#line 558 "LexerTokenizer.cpp"
yy56:
	++yycursor;
#line 124 "Lexer_re2c.cpp"
	{TOKEN(L_BRACKET);}
#line 563 "LexerTokenizer.cpp"
yy58:
	++yycursor;
#line 125 "Lexer_re2c.cpp"
	{TOKEN(R_BRACKET);}
#line 568 "LexerTokenizer.cpp"
yy60:
	++yycursor;
#line 126 "Lexer_re2c.cpp"
	{TOKEN(L_BRACE);}
#line 573 "LexerTokenizer.cpp"
yy62:
	++yycursor;
#line 127 "Lexer_re2c.cpp"
	{TOKEN(R_BRACE);}
#line 578 "LexerTokenizer.cpp"
yy64:
	yyaccept = 2;
	yych = *(yymarker = ++yycursor);
	switch (yych) {
	case 'd':	goto yy628;
	case 'e':	goto yy626;
	case 'i':	goto yy624;
	case 'p':	goto yy625;
	case 'u':	goto yy627;
	default:	goto yy65;
	}
yy65:
#line 129 "Lexer_re2c.cpp"
	{TOKEN(AT_SIGN);}
#line 593 "LexerTokenizer.cpp"
yy66:
	yych = *++yycursor;
	if (yych == 'a') goto yy587;
	if (yych == 'o') goto yy588;
	goto yy236;
yy67:
	yych = *++yycursor;
	if (yych <= 'g') {
		if (yych == 'a') goto yy555;
		goto yy236;
	} else {
		if (yych <= 'h') goto yy556;
		if (yych == 'o') goto yy557;
		goto yy236;
	}
yy68:
	yych = *++yycursor;
	switch (yych) {
	case '_':	goto yy505;
	case 'e':	goto yy506;
	case 'i':	goto yy507;
	case 't':	goto yy508;
	case 'w':	goto yy509;
	default:	goto yy236;
	}
yy69:
	yych = *++yycursor;
	if (yych <= '^') {
		if (yych <= '3') {
			if (yych == '1') goto yy448;
			if (yych <= '2') goto yy236;
			goto yy449;
		} else {
			if (yych <= '6') {
				if (yych <= '5') goto yy236;
				goto yy450;
			} else {
				if (yych == '8') goto yy451;
				goto yy236;
			}
		}
	} else {
		if (yych <= 'i') {
			if (yych <= 'b') {
				if (yych <= '_') goto yy453;
				goto yy236;
			} else {
				if (yych <= 'c') goto yy454;
				if (yych <= 'h') goto yy236;
				goto yy455;
			}
		} else {
			if (yych <= 'n') {
				if (yych <= 'm') goto yy236;
				goto yy456;
			} else {
				if (yych == 'w') goto yy457;
				goto yy236;
			}
		}
	}
yy70:
	yyaccept = 3;
	yych = *(yymarker = ++yycursor);
	if (yych <= '_') {
		if (yych == '"') goto yy233;
		if (yych <= '^') goto yy236;
		goto yy410;
	} else {
		if (yych <= 'l') {
			if (yych <= 'k') goto yy236;
			goto yy411;
		} else {
			if (yych == 'o') goto yy412;
			goto yy236;
		}
	}
yy71:
	yych = *++yycursor;
	if (yych == 'm') goto yy403;
	goto yy236;
yy72:
	yych = *++yycursor;
	if (yych == 't') goto yy396;
	goto yy236;
yy73:
	yych = *++yycursor;
	if (yych == 'e') goto yy382;
	if (yych == 'o') goto yy383;
	goto yy236;
yy74:
	yych = *++yycursor;
	if (yych == 'c') goto yy369;
	if (yych == 'h') goto yy370;
	goto yy236;
yy75:
	yych = *++yycursor;
	if (yych <= 'm') {
		if (yych == 'l') goto yy355;
		goto yy236;
	} else {
		if (yych <= 'n') goto yy356;
		if (yych == 'x') goto yy357;
		goto yy236;
	}
yy76:
	yych = *++yycursor;
	if (yych == 'e') goto yy335;
	goto yy236;
yy77:
	yych = *++yycursor;
	if (yych == 'o') goto yy331;
	goto yy236;
yy78:
	yych = *++yycursor;
	if (yych == 'r') goto yy324;
	if (yych == 'y') goto yy325;
	goto yy236;
yy79:
	yych = *++yycursor;
	if (yych == 'U') goto yy320;
	goto yy236;
yy80:
	yych = *++yycursor;
	if (yych == '_') goto yy298;
	goto yy236;
yy81:
	yych = *++yycursor;
	goto yy236;
yy82:
	yyaccept = 3;
	yych = *(yymarker = ++yycursor);
	if (yych == '"') goto yy233;
	if (yych == '\'') goto yy234;
	goto yy236;
yy83:
	yyaccept = 4;
	yych = *(yymarker = ++yycursor);
	if (yybm[0+yych] & 4) {
		goto yy180;
	}
	if (yych <= 'U') {
		if (yych <= 'B') {
			if (yych <= '/') {
				if (yych == '.') goto yy160;
			} else {
				if (yych <= '9') goto yy183;
				if (yych >= 'B') goto yy185;
			}
		} else {
			if (yych <= 'K') {
				if (yych == 'E') goto yy157;
			} else {
				if (yych <= 'L') goto yy188;
				if (yych >= 'U') goto yy186;
			}
		}
	} else {
		if (yych <= 'e') {
			if (yych <= 'a') {
				if (yych == 'X') goto yy179;
			} else {
				if (yych <= 'b') goto yy185;
				if (yych >= 'e') goto yy157;
			}
		} else {
			if (yych <= 't') {
				if (yych == 'l') goto yy187;
			} else {
				if (yych <= 'u') goto yy186;
				if (yych == 'x') goto yy179;
			}
		}
	}
yy84:
#line 258 "Lexer_re2c.cpp"
	{
                TOKEN(INT_CONST_DEC);
            }
#line 773 "LexerTokenizer.cpp"
yy85:
	yyaccept = 4;
	yych = *(yymarker = ++yycursor);
	if (yych <= 'L') {
		if (yych <= '9') {
			if (yych == '.') goto yy160;
			if (yych <= '/') goto yy84;
			goto yy158;
		} else {
			if (yych == 'E') goto yy157;
			if (yych <= 'K') goto yy84;
			goto yy165;
		}
	} else {
		if (yych <= 'e') {
			if (yych == 'U') goto yy163;
			if (yych <= 'd') goto yy84;
			goto yy157;
		} else {
			if (yych <= 'l') {
				if (yych <= 'k') goto yy84;
				goto yy164;
			} else {
				if (yych == 'u') goto yy163;
				goto yy84;
			}
		}
	}
yy86:
	yyaccept = 5;
	yych = *(yymarker = ++yycursor);
	if (yych <= 0x7F) {
		if (yych <= '&') {
			if (yych != '\n') goto yy143;
		} else {
			if (yych <= '\'') goto yy87;
			if (yych == '\\') goto yy150;
			goto yy143;
		}
	} else {
		if (yych <= 0xEF) {
			if (yych <= 0xC1) goto yy87;
			if (yych <= 0xDF) goto yy144;
			if (yych <= 0xE0) goto yy145;
			goto yy146;
		} else {
			if (yych <= 0xF0) goto yy147;
			if (yych <= 0xF3) goto yy148;
			if (yych <= 0xF4) goto yy149;
		}
	}
yy87:
#line 320 "Lexer_re2c.cpp"
	{
               this->token(tokType::ERROR_CHARACTER,
                           tokStart,
                           yycursor - tokStart,
                           lineno,
                           column);
               this->error(this->tokens.back());
               return false;
           }
#line 836 "LexerTokenizer.cpp"
yy88:
	yyaccept = 5;
	yych = *(yymarker = ++yycursor);
	if (yych <= '"') {
		if (yych == '\n') goto yy87;
		if (yych <= '!') goto yy97;
		goto yy105;
	} else {
		if (yych <= 0x7F) goto yy97;
		if (yych <= 0xC1) goto yy87;
		if (yych <= 0xF4) goto yy97;
		goto yy87;
	}
yy89:
	yych = *++yycursor;
	goto yy87;
yy90:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy89;
	goto yy2;
yy91:
	yych = *++yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy90;
	goto yy2;
yy92:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy90;
	goto yy2;
yy93:
	yych = *++yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy92;
	goto yy2;
yy94:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy92;
	goto yy2;
yy95:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy92;
	goto yy2;
yy96:
	++yycursor;
	yych = *yycursor;
yy97:
	if (yybm[256+yych] & 64) {
		goto yy96;
	}
	if (yych <= 0xDF) {
		if (yych <= '"') {
			if (yych <= '\n') goto yy2;
			goto yy142;
		} else {
			if (yych <= '\\') goto yy104;
			if (yych <= 0xC1) goto yy2;
		}
	} else {
		if (yych <= 0xF0) {
			if (yych <= 0xE0) goto yy99;
			if (yych <= 0xEF) goto yy100;
			goto yy101;
		} else {
			if (yych <= 0xF3) goto yy102;
			if (yych <= 0xF4) goto yy103;
			goto yy2;
		}
	}
yy98:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy96;
	goto yy2;
yy99:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy98;
	goto yy2;
yy100:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy98;
	goto yy2;
yy101:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy100;
	goto yy2;
yy102:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy100;
	goto yy2;
yy103:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy100;
	goto yy2;
yy104:
	++yycursor;
	yych = *yycursor;
	if (yych <= '?') {
		if (yych <= '.') {
			if (yych <= '%') {
				if (yych <= ' ') goto yy2;
				if (yych <= '"') goto yy96;
				goto yy2;
			} else {
				if (yych <= '\'') goto yy96;
				if (yych <= ',') goto yy2;
				goto yy96;
			}
		} else {
			if (yych <= '<') {
				if (yych <= '/') goto yy2;
				if (yych <= '9') goto yy140;
				goto yy2;
			} else {
				if (yych == '>') goto yy2;
				goto yy96;
			}
		}
	} else {
		if (yych <= '_') {
			if (yych <= '[') {
				if (yych <= '@') goto yy2;
				if (yych <= 'Z') goto yy96;
				goto yy2;
			} else {
				if (yych == ']') goto yy2;
				goto yy96;
			}
		} else {
			if (yych <= 'x') {
				if (yych <= '`') goto yy2;
				if (yych <= 'w') goto yy96;
				goto yy138;
			} else {
				if (yych <= 'z') goto yy96;
				if (yych == '~') goto yy96;
				goto yy2;
			}
		}
	}
yy105:
	yyctxmarker = yycursor + 1;
	yych = *++yycursor;
	if (yych <= 0xDF) {
		if (yych <= '"') {
			if (yych <= '!') goto yy108;
		} else {
			if (yych <= 0x7F) goto yy108;
			if (yych <= 0xC1) goto yy2;
			goto yy110;
		}
	} else {
		if (yych <= 0xF0) {
			if (yych <= 0xE0) goto yy111;
			if (yych <= 0xEF) goto yy112;
			goto yy113;
		} else {
			if (yych <= 0xF3) goto yy114;
			if (yych <= 0xF4) goto yy115;
			goto yy2;
		}
	}
yy106:
	++yycursor;
	yych = *yycursor;
	if (yybm[256+yych] & 128) {
		goto yy106;
	}
	if (yych <= 0xE0) {
		if (yych <= '\\') {
			if (yych <= '"') goto yy123;
			goto yy122;
		} else {
			if (yych <= 0xC1) goto yy2;
			if (yych <= 0xDF) goto yy116;
			goto yy117;
		}
	} else {
		if (yych <= 0xF0) {
			if (yych <= 0xEF) goto yy118;
			goto yy119;
		} else {
			if (yych <= 0xF3) goto yy120;
			if (yych <= 0xF4) goto yy121;
			goto yy2;
		}
	}
yy108:
	++yycursor;
	yycursor = yyctxmarker;
#line 312 "Lexer_re2c.cpp"
	{
               TOKEN(STRING_CONST);
           }
#line 1045 "LexerTokenizer.cpp"
yy110:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy108;
	goto yy2;
yy111:
	yych = *++yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy110;
	goto yy2;
yy112:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy110;
	goto yy2;
yy113:
	yych = *++yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy112;
	goto yy2;
yy114:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy112;
	goto yy2;
yy115:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy112;
	goto yy2;
yy116:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy106;
	goto yy2;
yy117:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy116;
	goto yy2;
yy118:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy116;
	goto yy2;
yy119:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy118;
	goto yy2;
yy120:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy118;
	goto yy2;
yy121:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy118;
	goto yy2;
yy122:
	++yycursor;
	yych = *yycursor;
	if (yybm[0+yych] & 2) {
		goto yy136;
	}
	if (yych <= '@') {
		if (yych <= ',') {
			if (yych <= '"') {
				if (yych <= ' ') goto yy2;
				goto yy106;
			} else {
				if (yych <= '%') goto yy2;
				if (yych <= '\'') goto yy106;
				goto yy2;
			}
		} else {
			if (yych <= '=') {
				if (yych <= '.') goto yy106;
				if (yych <= '<') goto yy2;
				goto yy106;
			} else {
				if (yych == '?') goto yy106;
				goto yy2;
			}
		}
	} else {
		if (yych <= '`') {
			if (yych <= '\\') {
				if (yych == '[') goto yy2;
				goto yy106;
			} else {
				if (yych <= ']') goto yy2;
				if (yych <= '_') goto yy106;
				goto yy2;
			}
		} else {
			if (yych <= 'z') {
				if (yych == 'x') goto yy134;
				goto yy106;
			} else {
				if (yych == '~') goto yy106;
				goto yy2;
			}
		}
	}
yy123:
	yych = *++yycursor;
	if (yych != '"') goto yy2;
	yych = *++yycursor;
	if (yych != '"') goto yy2;
	yyctxmarker = yycursor + 1;
	yych = *++yycursor;
	if (yych <= 0xDF) {
		if (yych <= '"') {
			if (yych >= '"') goto yy2;
		} else {
			if (yych <= 0x7F) goto yy126;
			if (yych <= 0xC1) goto yy2;
			goto yy128;
		}
	} else {
		if (yych <= 0xF0) {
			if (yych <= 0xE0) goto yy129;
			if (yych <= 0xEF) goto yy130;
			goto yy131;
		} else {
			if (yych <= 0xF3) goto yy132;
			if (yych <= 0xF4) goto yy133;
			goto yy2;
		}
	}
yy126:
	++yycursor;
	yycursor = yyctxmarker;
#line 304 "Lexer_re2c.cpp"
	{
               TOKEN(HERE_STRING_CONST);
           }
#line 1191 "LexerTokenizer.cpp"
yy128:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy126;
	goto yy2;
yy129:
	yych = *++yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy128;
	goto yy2;
yy130:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy128;
	goto yy2;
yy131:
	yych = *++yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy130;
	goto yy2;
yy132:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy130;
	goto yy2;
yy133:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy130;
	goto yy2;
yy134:
	++yycursor;
	yych = *yycursor;
	if (yybm[0+yych] & 1) {
		goto yy134;
	}
	if (yych <= 0xC1) {
		if (yych <= '[') {
			if (yych == '"') goto yy123;
			goto yy106;
		} else {
			if (yych <= '\\') goto yy122;
			if (yych <= 0x7F) goto yy106;
			goto yy2;
		}
	} else {
		if (yych <= 0xEF) {
			if (yych <= 0xDF) goto yy116;
			if (yych <= 0xE0) goto yy117;
			goto yy118;
		} else {
			if (yych <= 0xF0) goto yy119;
			if (yych <= 0xF3) goto yy120;
			if (yych <= 0xF4) goto yy121;
			goto yy2;
		}
	}
yy136:
	++yycursor;
	yych = *yycursor;
	if (yybm[0+yych] & 2) {
		goto yy136;
	}
	if (yych <= 0xC1) {
		if (yych <= '[') {
			if (yych == '"') goto yy123;
			goto yy106;
		} else {
			if (yych <= '\\') goto yy122;
			if (yych <= 0x7F) goto yy106;
			goto yy2;
		}
	} else {
		if (yych <= 0xEF) {
			if (yych <= 0xDF) goto yy116;
			if (yych <= 0xE0) goto yy117;
			goto yy118;
		} else {
			if (yych <= 0xF0) goto yy119;
			if (yych <= 0xF3) goto yy120;
			if (yych <= 0xF4) goto yy121;
			goto yy2;
		}
	}
yy138:
	++yycursor;
	yych = *yycursor;
	if (yych <= '\\') {
		if (yych <= '/') {
			if (yych <= '\n') {
				if (yych <= '\t') goto yy96;
				goto yy2;
			} else {
				if (yych == '"') goto yy142;
				goto yy96;
			}
		} else {
			if (yych <= '@') {
				if (yych <= '9') goto yy138;
				goto yy96;
			} else {
				if (yych <= 'F') goto yy138;
				if (yych <= '[') goto yy96;
				goto yy104;
			}
		}
	} else {
		if (yych <= 0xDF) {
			if (yych <= 'f') {
				if (yych <= '`') goto yy96;
				goto yy138;
			} else {
				if (yych <= 0x7F) goto yy96;
				if (yych <= 0xC1) goto yy2;
				goto yy98;
			}
		} else {
			if (yych <= 0xF0) {
				if (yych <= 0xE0) goto yy99;
				if (yych <= 0xEF) goto yy100;
				goto yy101;
			} else {
				if (yych <= 0xF3) goto yy102;
				if (yych <= 0xF4) goto yy103;
				goto yy2;
			}
		}
	}
yy140:
	++yycursor;
	yych = *yycursor;
	if (yych <= '\\') {
		if (yych <= '"') {
			if (yych == '\n') goto yy2;
			if (yych <= '!') goto yy96;
		} else {
			if (yych <= '/') goto yy96;
			if (yych <= '9') goto yy140;
			if (yych <= '[') goto yy96;
			goto yy104;
		}
	} else {
		if (yych <= 0xE0) {
			if (yych <= 0x7F) goto yy96;
			if (yych <= 0xC1) goto yy2;
			if (yych <= 0xDF) goto yy98;
			goto yy99;
		} else {
			if (yych <= 0xF0) {
				if (yych <= 0xEF) goto yy100;
				goto yy101;
			} else {
				if (yych <= 0xF3) goto yy102;
				if (yych <= 0xF4) goto yy103;
				goto yy2;
			}
		}
	}
yy142:
	yyctxmarker = yycursor + 1;
	yych = *++yycursor;
	if (yych <= 0xDF) {
		if (yych <= '"') {
			if (yych <= '!') goto yy108;
			goto yy2;
		} else {
			if (yych <= 0x7F) goto yy108;
			if (yych <= 0xC1) goto yy2;
			goto yy110;
		}
	} else {
		if (yych <= 0xF0) {
			if (yych <= 0xE0) goto yy111;
			if (yych <= 0xEF) goto yy112;
			goto yy113;
		} else {
			if (yych <= 0xF3) goto yy114;
			if (yych <= 0xF4) goto yy115;
			goto yy2;
		}
	}
yy143:
	yych = *++yycursor;
	if (yych == '\'') goto yy155;
	goto yy2;
yy144:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy143;
	goto yy2;
yy145:
	yych = *++yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy144;
	goto yy2;
yy146:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy144;
	goto yy2;
yy147:
	yych = *++yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy146;
	goto yy2;
yy148:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy146;
	goto yy2;
yy149:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy146;
	goto yy2;
yy150:
	yych = *++yycursor;
	if (yych <= '@') {
		if (yych <= ',') {
			if (yych <= '"') {
				if (yych <= ' ') goto yy154;
				goto yy143;
			} else {
				if (yych <= '%') goto yy154;
				if (yych <= '\'') goto yy143;
				goto yy154;
			}
		} else {
			if (yych <= '=') {
				if (yych <= '.') goto yy143;
				if (yych <= '<') goto yy154;
				goto yy143;
			} else {
				if (yych == '?') goto yy143;
				goto yy154;
			}
		}
	} else {
		if (yych <= '`') {
			if (yych <= '\\') {
				if (yych == '[') goto yy154;
				goto yy143;
			} else {
				if (yych <= ']') goto yy154;
				if (yych <= '_') goto yy143;
				goto yy154;
			}
		} else {
			if (yych <= 'z') {
				if (yych != 'x') goto yy143;
			} else {
				if (yych == '~') goto yy143;
				goto yy154;
			}
		}
	}
yy151:
	++yycursor;
	yych = *yycursor;
	if (yych <= '9') {
		if (yych == '\'') goto yy155;
		if (yych <= '/') goto yy2;
		goto yy151;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy2;
			goto yy151;
		} else {
			if (yych <= '`') goto yy2;
			if (yych <= 'f') goto yy151;
			goto yy2;
		}
	}
yy153:
	++yycursor;
	yych = *yycursor;
yy154:
	if (yych == '\'') goto yy155;
	if (yych <= '/') goto yy2;
	if (yych <= '9') goto yy153;
	goto yy2;
yy155:
	++yycursor;
#line 293 "Lexer_re2c.cpp"
	{
                TOKEN(CHAR_CONST);
            }
#line 1479 "LexerTokenizer.cpp"
yy157:
	yych = *++yycursor;
	if (yych <= ',') {
		if (yych == '+') goto yy176;
		goto yy2;
	} else {
		if (yych <= '-') goto yy176;
		if (yych <= '/') goto yy2;
		if (yych <= '9') goto yy177;
		goto yy2;
	}
yy158:
	yyaccept = 4;
	yymarker = ++yycursor;
	yych = *yycursor;
	if (yych <= 'L') {
		if (yych <= '9') {
			if (yych == '.') goto yy160;
			if (yych <= '/') goto yy84;
			goto yy158;
		} else {
			if (yych == 'E') goto yy157;
			if (yych <= 'K') goto yy84;
			goto yy165;
		}
	} else {
		if (yych <= 'e') {
			if (yych == 'U') goto yy163;
			if (yych <= 'd') goto yy84;
			goto yy157;
		} else {
			if (yych <= 'l') {
				if (yych <= 'k') goto yy84;
				goto yy164;
			} else {
				if (yych == 'u') goto yy163;
				goto yy84;
			}
		}
	}
yy160:
	yyaccept = 6;
	yymarker = ++yycursor;
	yych = *yycursor;
	if (yych <= 'K') {
		if (yych <= 'D') {
			if (yych <= '/') goto yy162;
			if (yych <= '9') goto yy160;
		} else {
			if (yych <= 'E') goto yy171;
			if (yych <= 'F') goto yy172;
		}
	} else {
		if (yych <= 'e') {
			if (yych <= 'L') goto yy172;
			if (yych >= 'e') goto yy171;
		} else {
			if (yych <= 'f') goto yy172;
			if (yych == 'l') goto yy172;
		}
	}
yy162:
#line 276 "Lexer_re2c.cpp"
	{
                TOKEN(FLOAT_CONST);
            }
#line 1546 "LexerTokenizer.cpp"
yy163:
	yych = *++yycursor;
	if (yych == 'L') goto yy169;
	if (yych == 'l') goto yy170;
	goto yy84;
yy164:
	yych = *++yycursor;
	if (yych <= 'k') {
		if (yych == 'U') goto yy166;
		goto yy84;
	} else {
		if (yych <= 'l') goto yy168;
		if (yych == 'u') goto yy166;
		goto yy84;
	}
yy165:
	yych = *++yycursor;
	if (yych <= 'T') {
		if (yych == 'L') goto yy167;
		goto yy84;
	} else {
		if (yych <= 'U') goto yy166;
		if (yych != 'u') goto yy84;
	}
yy166:
	yych = *++yycursor;
	goto yy84;
yy167:
	yych = *++yycursor;
	if (yych == 'U') goto yy166;
	if (yych == 'u') goto yy166;
	goto yy84;
yy168:
	yych = *++yycursor;
	if (yych == 'U') goto yy166;
	if (yych == 'u') goto yy166;
	goto yy84;
yy169:
	yych = *++yycursor;
	if (yych == 'L') goto yy166;
	goto yy84;
yy170:
	yych = *++yycursor;
	if (yych == 'l') goto yy166;
	goto yy84;
yy171:
	yych = *++yycursor;
	if (yych <= ',') {
		if (yych == '+') goto yy173;
		goto yy2;
	} else {
		if (yych <= '-') goto yy173;
		if (yych <= '/') goto yy2;
		if (yych <= '9') goto yy174;
		goto yy2;
	}
yy172:
	yych = *++yycursor;
	goto yy162;
yy173:
	yych = *++yycursor;
	if (yych <= '/') goto yy2;
	if (yych >= ':') goto yy2;
yy174:
	++yycursor;
	yych = *yycursor;
	if (yych <= 'K') {
		if (yych <= '9') {
			if (yych <= '/') goto yy162;
			goto yy174;
		} else {
			if (yych == 'F') goto yy172;
			goto yy162;
		}
	} else {
		if (yych <= 'f') {
			if (yych <= 'L') goto yy172;
			if (yych <= 'e') goto yy162;
			goto yy172;
		} else {
			if (yych == 'l') goto yy172;
			goto yy162;
		}
	}
yy176:
	yych = *++yycursor;
	if (yych <= '/') goto yy2;
	if (yych >= ':') goto yy2;
yy177:
	++yycursor;
	yych = *yycursor;
	if (yych <= 'K') {
		if (yych <= '9') {
			if (yych <= '/') goto yy162;
			goto yy177;
		} else {
			if (yych == 'F') goto yy172;
			goto yy162;
		}
	} else {
		if (yych <= 'f') {
			if (yych <= 'L') goto yy172;
			if (yych <= 'e') goto yy162;
			goto yy172;
		} else {
			if (yych == 'l') goto yy172;
			goto yy162;
		}
	}
yy179:
	yych = *++yycursor;
	if (yych <= '9') {
		if (yych == '.') goto yy216;
		if (yych <= '/') goto yy2;
		goto yy213;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy2;
			goto yy213;
		} else {
			if (yych <= '`') goto yy2;
			if (yych <= 'f') goto yy213;
			goto yy2;
		}
	}
yy180:
	yyaccept = 7;
	yymarker = ++yycursor;
	yych = *yycursor;
	if (yybm[0+yych] & 4) {
		goto yy180;
	}
	if (yych <= 'L') {
		if (yych <= '9') {
			if (yych == '.') goto yy160;
			if (yych >= '0') goto yy183;
		} else {
			if (yych == 'E') goto yy157;
			if (yych >= 'L') goto yy207;
		}
	} else {
		if (yych <= 'e') {
			if (yych == 'U') goto yy205;
			if (yych >= 'e') goto yy157;
		} else {
			if (yych <= 'l') {
				if (yych >= 'l') goto yy206;
			} else {
				if (yych == 'u') goto yy205;
			}
		}
	}
yy182:
#line 262 "Lexer_re2c.cpp"
	{
                TOKEN(INT_CONST_OCT);
            }
#line 1704 "LexerTokenizer.cpp"
yy183:
	++yycursor;
	yych = *yycursor;
	if (yych <= '9') {
		if (yych == '.') goto yy160;
		if (yych <= '/') goto yy2;
		goto yy183;
	} else {
		if (yych <= 'E') {
			if (yych <= 'D') goto yy2;
			goto yy157;
		} else {
			if (yych == 'e') goto yy157;
			goto yy2;
		}
	}
yy185:
	yych = *++yycursor;
	if (yybm[0+yych] & 8) {
		goto yy194;
	}
	goto yy2;
yy186:
	yych = *++yycursor;
	if (yych == 'L') goto yy192;
	if (yych == 'l') goto yy193;
	goto yy84;
yy187:
	yych = *++yycursor;
	if (yych <= 'k') {
		if (yych == 'U') goto yy189;
		goto yy84;
	} else {
		if (yych <= 'l') goto yy191;
		if (yych == 'u') goto yy189;
		goto yy84;
	}
yy188:
	yych = *++yycursor;
	if (yych <= 'T') {
		if (yych == 'L') goto yy190;
		goto yy84;
	} else {
		if (yych <= 'U') goto yy189;
		if (yych != 'u') goto yy84;
	}
yy189:
	yych = *++yycursor;
	goto yy84;
yy190:
	yych = *++yycursor;
	if (yych == 'U') goto yy189;
	if (yych == 'u') goto yy189;
	goto yy84;
yy191:
	yych = *++yycursor;
	if (yych == 'U') goto yy189;
	if (yych == 'u') goto yy189;
	goto yy84;
yy192:
	yych = *++yycursor;
	if (yych == 'L') goto yy189;
	goto yy84;
yy193:
	yych = *++yycursor;
	if (yych == 'l') goto yy189;
	goto yy84;
yy194:
	++yycursor;
	yych = *yycursor;
	if (yybm[0+yych] & 8) {
		goto yy194;
	}
	if (yych <= 'U') {
		if (yych == 'L') goto yy199;
		if (yych >= 'U') goto yy197;
	} else {
		if (yych <= 'l') {
			if (yych >= 'l') goto yy198;
		} else {
			if (yych == 'u') goto yy197;
		}
	}
yy196:
#line 270 "Lexer_re2c.cpp"
	{
                TOKEN(INT_CONST_BIN);
            }
#line 1793 "LexerTokenizer.cpp"
yy197:
	yych = *++yycursor;
	if (yych == 'L') goto yy203;
	if (yych == 'l') goto yy204;
	goto yy196;
yy198:
	yych = *++yycursor;
	if (yych <= 'k') {
		if (yych == 'U') goto yy200;
		goto yy196;
	} else {
		if (yych <= 'l') goto yy202;
		if (yych == 'u') goto yy200;
		goto yy196;
	}
yy199:
	yych = *++yycursor;
	if (yych <= 'T') {
		if (yych == 'L') goto yy201;
		goto yy196;
	} else {
		if (yych <= 'U') goto yy200;
		if (yych != 'u') goto yy196;
	}
yy200:
	yych = *++yycursor;
	goto yy196;
yy201:
	yych = *++yycursor;
	if (yych == 'U') goto yy200;
	if (yych == 'u') goto yy200;
	goto yy196;
yy202:
	yych = *++yycursor;
	if (yych == 'U') goto yy200;
	if (yych == 'u') goto yy200;
	goto yy196;
yy203:
	yych = *++yycursor;
	if (yych == 'L') goto yy200;
	goto yy196;
yy204:
	yych = *++yycursor;
	if (yych == 'l') goto yy200;
	goto yy196;
yy205:
	yych = *++yycursor;
	if (yych == 'L') goto yy211;
	if (yych == 'l') goto yy212;
	goto yy182;
yy206:
	yych = *++yycursor;
	if (yych <= 'k') {
		if (yych == 'U') goto yy208;
		goto yy182;
	} else {
		if (yych <= 'l') goto yy210;
		if (yych == 'u') goto yy208;
		goto yy182;
	}
yy207:
	yych = *++yycursor;
	if (yych <= 'T') {
		if (yych == 'L') goto yy209;
		goto yy182;
	} else {
		if (yych <= 'U') goto yy208;
		if (yych != 'u') goto yy182;
	}
yy208:
	yych = *++yycursor;
	goto yy182;
yy209:
	yych = *++yycursor;
	if (yych == 'U') goto yy208;
	if (yych == 'u') goto yy208;
	goto yy182;
yy210:
	yych = *++yycursor;
	if (yych == 'U') goto yy208;
	if (yych == 'u') goto yy208;
	goto yy182;
yy211:
	yych = *++yycursor;
	if (yych == 'L') goto yy208;
	goto yy182;
yy212:
	yych = *++yycursor;
	if (yych == 'l') goto yy208;
	goto yy182;
yy213:
	yyaccept = 8;
	yymarker = ++yycursor;
	yych = *yycursor;
	if (yych <= 'P') {
		if (yych <= '@') {
			if (yych <= '.') {
				if (yych >= '.') goto yy217;
			} else {
				if (yych <= '/') goto yy215;
				if (yych <= '9') goto yy213;
			}
		} else {
			if (yych <= 'K') {
				if (yych <= 'F') goto yy213;
			} else {
				if (yych <= 'L') goto yy227;
				if (yych >= 'P') goto yy219;
			}
		}
	} else {
		if (yych <= 'k') {
			if (yych <= 'U') {
				if (yych >= 'U') goto yy225;
			} else {
				if (yych <= '`') goto yy215;
				if (yych <= 'f') goto yy213;
			}
		} else {
			if (yych <= 'p') {
				if (yych <= 'l') goto yy226;
				if (yych >= 'p') goto yy219;
			} else {
				if (yych == 'u') goto yy225;
			}
		}
	}
yy215:
#line 266 "Lexer_re2c.cpp"
	{
                TOKEN(INT_CONST_HEX);
            }
#line 1926 "LexerTokenizer.cpp"
yy216:
	yych = *++yycursor;
	if (yych == 'P') goto yy2;
	if (yych == 'p') goto yy2;
	goto yy218;
yy217:
	++yycursor;
	yych = *yycursor;
yy218:
	if (yych <= 'O') {
		if (yych <= '9') {
			if (yych <= '/') goto yy2;
			goto yy217;
		} else {
			if (yych <= '@') goto yy2;
			if (yych <= 'F') goto yy217;
			goto yy2;
		}
	} else {
		if (yych <= 'f') {
			if (yych <= 'P') goto yy219;
			if (yych <= '`') goto yy2;
			goto yy217;
		} else {
			if (yych != 'p') goto yy2;
		}
	}
yy219:
	yych = *++yycursor;
	if (yych <= ',') {
		if (yych != '+') goto yy2;
	} else {
		if (yych <= '-') goto yy220;
		if (yych <= '/') goto yy2;
		if (yych <= '9') goto yy221;
		goto yy2;
	}
yy220:
	yych = *++yycursor;
	if (yych <= '/') goto yy2;
	if (yych >= ':') goto yy2;
yy221:
	++yycursor;
	yych = *yycursor;
	if (yych <= 'K') {
		if (yych <= '9') {
			if (yych >= '0') goto yy221;
		} else {
			if (yych == 'F') goto yy224;
		}
	} else {
		if (yych <= 'f') {
			if (yych <= 'L') goto yy224;
			if (yych >= 'f') goto yy224;
		} else {
			if (yych == 'l') goto yy224;
		}
	}
yy223:
#line 282 "Lexer_re2c.cpp"
	{
                TOKEN(FLOAT_CONST_HEX);
            }
#line 1990 "LexerTokenizer.cpp"
yy224:
	yych = *++yycursor;
	goto yy223;
yy225:
	yych = *++yycursor;
	if (yych == 'L') goto yy231;
	if (yych == 'l') goto yy232;
	goto yy215;
yy226:
	yych = *++yycursor;
	if (yych <= 'k') {
		if (yych == 'U') goto yy228;
		goto yy215;
	} else {
		if (yych <= 'l') goto yy230;
		if (yych == 'u') goto yy228;
		goto yy215;
	}
yy227:
	yych = *++yycursor;
	if (yych <= 'T') {
		if (yych == 'L') goto yy229;
		goto yy215;
	} else {
		if (yych <= 'U') goto yy228;
		if (yych != 'u') goto yy215;
	}
yy228:
	yych = *++yycursor;
	goto yy215;
yy229:
	yych = *++yycursor;
	if (yych == 'U') goto yy228;
	if (yych == 'u') goto yy228;
	goto yy215;
yy230:
	yych = *++yycursor;
	if (yych == 'U') goto yy228;
	if (yych == 'u') goto yy228;
	goto yy215;
yy231:
	yych = *++yycursor;
	if (yych == 'L') goto yy228;
	goto yy215;
yy232:
	yych = *++yycursor;
	if (yych == 'l') goto yy228;
	goto yy215;
yy233:
	yych = *++yycursor;
	if (yych == '"') goto yy251;
	goto yy253;
yy234:
	yych = *++yycursor;
	if (yych <= 0x7F) {
		if (yych <= '&') {
			if (yych == '\n') goto yy2;
			goto yy237;
		} else {
			if (yych <= '\'') goto yy2;
			if (yych == '\\') goto yy244;
			goto yy237;
		}
	} else {
		if (yych <= 0xEF) {
			if (yych <= 0xC1) goto yy2;
			if (yych <= 0xDF) goto yy238;
			if (yych <= 0xE0) goto yy239;
			goto yy240;
		} else {
			if (yych <= 0xF0) goto yy241;
			if (yych <= 0xF3) goto yy242;
			if (yych <= 0xF4) goto yy243;
			goto yy2;
		}
	}
yy235:
	++yycursor;
	yych = *yycursor;
yy236:
	if (yybm[0+yych] & 16) {
		goto yy235;
	}
	goto yy14;
yy237:
	yych = *++yycursor;
	if (yych == '\'') goto yy249;
	goto yy2;
yy238:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy237;
	goto yy2;
yy239:
	yych = *++yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy238;
	goto yy2;
yy240:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy238;
	goto yy2;
yy241:
	yych = *++yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy240;
	goto yy2;
yy242:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy240;
	goto yy2;
yy243:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy240;
	goto yy2;
yy244:
	yych = *++yycursor;
	if (yych <= '@') {
		if (yych <= ',') {
			if (yych <= '"') {
				if (yych <= ' ') goto yy248;
				goto yy237;
			} else {
				if (yych <= '%') goto yy248;
				if (yych <= '\'') goto yy237;
				goto yy248;
			}
		} else {
			if (yych <= '=') {
				if (yych <= '.') goto yy237;
				if (yych <= '<') goto yy248;
				goto yy237;
			} else {
				if (yych == '?') goto yy237;
				goto yy248;
			}
		}
	} else {
		if (yych <= '`') {
			if (yych <= '\\') {
				if (yych == '[') goto yy248;
				goto yy237;
			} else {
				if (yych <= ']') goto yy248;
				if (yych <= '_') goto yy237;
				goto yy248;
			}
		} else {
			if (yych <= 'z') {
				if (yych != 'x') goto yy237;
			} else {
				if (yych == '~') goto yy237;
				goto yy248;
			}
		}
	}
yy245:
	++yycursor;
	yych = *yycursor;
	if (yych <= '9') {
		if (yych == '\'') goto yy249;
		if (yych <= '/') goto yy2;
		goto yy245;
	} else {
		if (yych <= 'F') {
			if (yych <= '@') goto yy2;
			goto yy245;
		} else {
			if (yych <= '`') goto yy2;
			if (yych <= 'f') goto yy245;
			goto yy2;
		}
	}
yy247:
	++yycursor;
	yych = *yycursor;
yy248:
	if (yych == '\'') goto yy249;
	if (yych <= '/') goto yy2;
	if (yych <= '9') goto yy247;
	goto yy2;
yy249:
	++yycursor;
#line 297 "Lexer_re2c.cpp"
	{
                TOKEN(WCHAR_CONST);
            }
#line 2181 "LexerTokenizer.cpp"
yy251:
	yyctxmarker = yycursor + 1;
	yych = *++yycursor;
	if (yych <= 0xDF) {
		if (yych <= '"') {
			if (yych <= '!') goto yy266;
			goto yy274;
		} else {
			if (yych <= 0x7F) goto yy266;
			if (yych <= 0xC1) goto yy2;
			goto yy268;
		}
	} else {
		if (yych <= 0xF0) {
			if (yych <= 0xE0) goto yy269;
			if (yych <= 0xEF) goto yy270;
			goto yy271;
		} else {
			if (yych <= 0xF3) goto yy272;
			if (yych <= 0xF4) goto yy273;
			goto yy2;
		}
	}
yy252:
	++yycursor;
	yych = *yycursor;
yy253:
	if (yych <= 0x7F) {
		if (yych <= '!') {
			if (yych == '\n') goto yy2;
			goto yy252;
		} else {
			if (yych <= '"') goto yy265;
			if (yych == '\\') goto yy260;
			goto yy252;
		}
	} else {
		if (yych <= 0xEF) {
			if (yych <= 0xC1) goto yy2;
			if (yych <= 0xDF) goto yy254;
			if (yych <= 0xE0) goto yy255;
			goto yy256;
		} else {
			if (yych <= 0xF0) goto yy257;
			if (yych <= 0xF3) goto yy258;
			if (yych <= 0xF4) goto yy259;
			goto yy2;
		}
	}
yy254:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy252;
	goto yy2;
yy255:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy254;
	goto yy2;
yy256:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy254;
	goto yy2;
yy257:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy256;
	goto yy2;
yy258:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy256;
	goto yy2;
yy259:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy256;
	goto yy2;
yy260:
	++yycursor;
	yych = *yycursor;
	if (yych <= '?') {
		if (yych <= '.') {
			if (yych <= '%') {
				if (yych <= ' ') goto yy2;
				if (yych <= '"') goto yy252;
				goto yy2;
			} else {
				if (yych <= '\'') goto yy252;
				if (yych <= ',') goto yy2;
				goto yy252;
			}
		} else {
			if (yych <= '<') {
				if (yych <= '/') goto yy2;
				if (yych <= '9') goto yy263;
				goto yy2;
			} else {
				if (yych == '>') goto yy2;
				goto yy252;
			}
		}
	} else {
		if (yych <= '_') {
			if (yych <= '[') {
				if (yych <= '@') goto yy2;
				if (yych <= 'Z') goto yy252;
				goto yy2;
			} else {
				if (yych == ']') goto yy2;
				goto yy252;
			}
		} else {
			if (yych <= 'x') {
				if (yych <= '`') goto yy2;
				if (yych <= 'w') goto yy252;
			} else {
				if (yych <= 'z') goto yy252;
				if (yych == '~') goto yy252;
				goto yy2;
			}
		}
	}
yy261:
	++yycursor;
	yych = *yycursor;
	if (yych <= '\\') {
		if (yych <= '/') {
			if (yych <= '\n') {
				if (yych <= '\t') goto yy252;
				goto yy2;
			} else {
				if (yych == '"') goto yy265;
				goto yy252;
			}
		} else {
			if (yych <= '@') {
				if (yych <= '9') goto yy261;
				goto yy252;
			} else {
				if (yych <= 'F') goto yy261;
				if (yych <= '[') goto yy252;
				goto yy260;
			}
		}
	} else {
		if (yych <= 0xDF) {
			if (yych <= 'f') {
				if (yych <= '`') goto yy252;
				goto yy261;
			} else {
				if (yych <= 0x7F) goto yy252;
				if (yych <= 0xC1) goto yy2;
				goto yy254;
			}
		} else {
			if (yych <= 0xF0) {
				if (yych <= 0xE0) goto yy255;
				if (yych <= 0xEF) goto yy256;
				goto yy257;
			} else {
				if (yych <= 0xF3) goto yy258;
				if (yych <= 0xF4) goto yy259;
				goto yy2;
			}
		}
	}
yy263:
	++yycursor;
	yych = *yycursor;
	if (yych <= '\\') {
		if (yych <= '"') {
			if (yych == '\n') goto yy2;
			if (yych <= '!') goto yy252;
		} else {
			if (yych <= '/') goto yy252;
			if (yych <= '9') goto yy263;
			if (yych <= '[') goto yy252;
			goto yy260;
		}
	} else {
		if (yych <= 0xE0) {
			if (yych <= 0x7F) goto yy252;
			if (yych <= 0xC1) goto yy2;
			if (yych <= 0xDF) goto yy254;
			goto yy255;
		} else {
			if (yych <= 0xF0) {
				if (yych <= 0xEF) goto yy256;
				goto yy257;
			} else {
				if (yych <= 0xF3) goto yy258;
				if (yych <= 0xF4) goto yy259;
				goto yy2;
			}
		}
	}
yy265:
	yyctxmarker = yycursor + 1;
	yych = *++yycursor;
	if (yych <= 0xDF) {
		if (yych <= '"') {
			if (yych >= '"') goto yy2;
		} else {
			if (yych <= 0x7F) goto yy266;
			if (yych <= 0xC1) goto yy2;
			goto yy268;
		}
	} else {
		if (yych <= 0xF0) {
			if (yych <= 0xE0) goto yy269;
			if (yych <= 0xEF) goto yy270;
			goto yy271;
		} else {
			if (yych <= 0xF3) goto yy272;
			if (yych <= 0xF4) goto yy273;
			goto yy2;
		}
	}
yy266:
	++yycursor;
	yycursor = yyctxmarker;
#line 316 "Lexer_re2c.cpp"
	{
               TOKEN(WSTRING_CONST);
           }
#line 2415 "LexerTokenizer.cpp"
yy268:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy266;
	goto yy2;
yy269:
	yych = *++yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy268;
	goto yy2;
yy270:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy268;
	goto yy2;
yy271:
	yych = *++yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy270;
	goto yy2;
yy272:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy270;
	goto yy2;
yy273:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy270;
	goto yy2;
yy274:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0xC1) {
		if (yych <= '[') {
			if (yych == '"') goto yy283;
			goto yy274;
		} else {
			if (yych <= '\\') goto yy282;
			if (yych <= 0x7F) goto yy274;
			goto yy2;
		}
	} else {
		if (yych <= 0xEF) {
			if (yych <= 0xDF) goto yy276;
			if (yych <= 0xE0) goto yy277;
			goto yy278;
		} else {
			if (yych <= 0xF0) goto yy279;
			if (yych <= 0xF3) goto yy280;
			if (yych <= 0xF4) goto yy281;
			goto yy2;
		}
	}
yy276:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy274;
	goto yy2;
yy277:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy276;
	goto yy2;
yy278:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy276;
	goto yy2;
yy279:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy278;
	goto yy2;
yy280:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy278;
	goto yy2;
yy281:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy278;
	goto yy2;
yy282:
	++yycursor;
	yych = *yycursor;
	if (yych <= '?') {
		if (yych <= '.') {
			if (yych <= '%') {
				if (yych <= ' ') goto yy2;
				if (yych <= '"') goto yy274;
				goto yy2;
			} else {
				if (yych <= '\'') goto yy274;
				if (yych <= ',') goto yy2;
				goto yy274;
			}
		} else {
			if (yych <= '<') {
				if (yych <= '/') goto yy2;
				if (yych <= '9') goto yy296;
				goto yy2;
			} else {
				if (yych == '>') goto yy2;
				goto yy274;
			}
		}
	} else {
		if (yych <= '_') {
			if (yych <= '[') {
				if (yych <= '@') goto yy2;
				if (yych <= 'Z') goto yy274;
				goto yy2;
			} else {
				if (yych == ']') goto yy2;
				goto yy274;
			}
		} else {
			if (yych <= 'x') {
				if (yych <= '`') goto yy2;
				if (yych <= 'w') goto yy274;
				goto yy294;
			} else {
				if (yych <= 'z') goto yy274;
				if (yych == '~') goto yy274;
				goto yy2;
			}
		}
	}
yy283:
	yych = *++yycursor;
	if (yych != '"') goto yy2;
	yych = *++yycursor;
	if (yych != '"') goto yy2;
	yyctxmarker = yycursor + 1;
	yych = *++yycursor;
	if (yych <= 0xDF) {
		if (yych <= '"') {
			if (yych >= '"') goto yy2;
		} else {
			if (yych <= 0x7F) goto yy286;
			if (yych <= 0xC1) goto yy2;
			goto yy288;
		}
	} else {
		if (yych <= 0xF0) {
			if (yych <= 0xE0) goto yy289;
			if (yych <= 0xEF) goto yy290;
			goto yy291;
		} else {
			if (yych <= 0xF3) goto yy292;
			if (yych <= 0xF4) goto yy293;
			goto yy2;
		}
	}
yy286:
	++yycursor;
	yycursor = yyctxmarker;
#line 308 "Lexer_re2c.cpp"
	{
               TOKEN(HERE_WSTRING_CONST);
           }
#line 2585 "LexerTokenizer.cpp"
yy288:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy286;
	goto yy2;
yy289:
	yych = *++yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy288;
	goto yy2;
yy290:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy288;
	goto yy2;
yy291:
	yych = *++yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy290;
	goto yy2;
yy292:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy290;
	goto yy2;
yy293:
	yych = *++yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy290;
	goto yy2;
yy294:
	++yycursor;
	yych = *yycursor;
	if (yych <= '`') {
		if (yych <= '9') {
			if (yych == '"') goto yy283;
			if (yych <= '/') goto yy274;
			goto yy294;
		} else {
			if (yych <= 'F') {
				if (yych <= '@') goto yy274;
				goto yy294;
			} else {
				if (yych == '\\') goto yy282;
				goto yy274;
			}
		}
	} else {
		if (yych <= 0xE0) {
			if (yych <= 0x7F) {
				if (yych <= 'f') goto yy294;
				goto yy274;
			} else {
				if (yych <= 0xC1) goto yy2;
				if (yych <= 0xDF) goto yy276;
				goto yy277;
			}
		} else {
			if (yych <= 0xF0) {
				if (yych <= 0xEF) goto yy278;
				goto yy279;
			} else {
				if (yych <= 0xF3) goto yy280;
				if (yych <= 0xF4) goto yy281;
				goto yy2;
			}
		}
	}
yy296:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) {
		if (yych <= '/') {
			if (yych == '"') goto yy283;
			goto yy274;
		} else {
			if (yych <= '9') goto yy296;
			if (yych == '\\') goto yy282;
			goto yy274;
		}
	} else {
		if (yych <= 0xEF) {
			if (yych <= 0xC1) goto yy2;
			if (yych <= 0xDF) goto yy276;
			if (yych <= 0xE0) goto yy277;
			goto yy278;
		} else {
			if (yych <= 0xF0) goto yy279;
			if (yych <= 0xF3) goto yy280;
			if (yych <= 0xF4) goto yy281;
			goto yy2;
		}
	}
yy298:
	yych = *++yycursor;
	if (yych == 'f') goto yy299;
	if (yych == 'p') goto yy300;
	goto yy236;
yy299:
	yych = *++yycursor;
	if (yych == 'u') goto yy314;
	goto yy236;
yy300:
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	yych = *++yycursor;
	if (yych != 'y') goto yy236;
	yych = *++yycursor;
	if (yych != '_') goto yy236;
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	yych = *++yycursor;
	if (yych != 'u') goto yy236;
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	yych = *++yycursor;
	if (yych != '_') goto yy236;
	yych = *++yycursor;
	if (yych != '_') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 247 "Lexer_re2c.cpp"
	{TOKEN(__PRETTY_FUNC__);}
#line 2719 "LexerTokenizer.cpp"
yy314:
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	yych = *++yycursor;
	if (yych != '_') goto yy236;
	yych = *++yycursor;
	if (yych != '_') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 246 "Lexer_re2c.cpp"
	{TOKEN(__FUNC__);}
#line 2735 "LexerTokenizer.cpp"
yy320:
	yych = *++yycursor;
	if (yych != 'L') goto yy236;
	yych = *++yycursor;
	if (yych != 'L') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 245 "Lexer_re2c.cpp"
	{TOKEN(NULL_VAL);}
#line 2747 "LexerTokenizer.cpp"
yy324:
	yych = *++yycursor;
	if (yych == 'e') goto yy327;
	goto yy236;
yy325:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 241 "Lexer_re2c.cpp"
	{TOKEN(BY);}
#line 2759 "LexerTokenizer.cpp"
yy327:
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 'k') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 223 "Lexer_re2c.cpp"
	{TOKEN(BREAK);}
#line 2771 "LexerTokenizer.cpp"
yy331:
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	yych = *++yycursor;
	if (yych != 'o') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 221 "Lexer_re2c.cpp"
	{TOKEN(GOTO);}
#line 2783 "LexerTokenizer.cpp"
yy335:
	yych = *++yycursor;
	if (yych <= 'r') {
		if (yych != 'g') goto yy236;
	} else {
		if (yych <= 's') goto yy337;
		if (yych <= 't') goto yy338;
		goto yy236;
	}
	yych = *++yycursor;
	if (yych == 'i') goto yy349;
	goto yy236;
yy337:
	yych = *++yycursor;
	if (yych == 't') goto yy343;
	goto yy236;
yy338:
	yych = *++yycursor;
	if (yych != 'u') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 199 "Lexer_re2c.cpp"
	{TOKEN(RETURN);}
#line 2813 "LexerTokenizer.cpp"
yy343:
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 195 "Lexer_re2c.cpp"
	{TOKEN(RESTRICT_QUALIFIER);}
#line 2829 "LexerTokenizer.cpp"
yy349:
	yych = *++yycursor;
	if (yych != 's') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 189 "Lexer_re2c.cpp"
	{TOKEN(REGISTER_SPECIFIER);}
#line 2845 "LexerTokenizer.cpp"
yy355:
	yych = *++yycursor;
	if (yych == 's') goto yy366;
	goto yy236;
yy356:
	yych = *++yycursor;
	if (yych == 'u') goto yy363;
	goto yy236;
yy357:
	yych = *++yycursor;
	if (yych != 'p') goto yy236;
	yych = *++yycursor;
	if (yych != 'o') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 186 "Lexer_re2c.cpp"
	{TOKEN(EXPORT);}
#line 2869 "LexerTokenizer.cpp"
yy363:
	yych = *++yycursor;
	if (yych != 'm') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 178 "Lexer_re2c.cpp"
	{TOKEN(ENUM);}
#line 2879 "LexerTokenizer.cpp"
yy366:
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 218 "Lexer_re2c.cpp"
	{TOKEN(ELSE);}
#line 2889 "LexerTokenizer.cpp"
yy369:
	yych = *++yycursor;
	if (yych == 'h') goto yy378;
	goto yy236;
yy370:
	yych = *++yycursor;
	if (yych == 'e') goto yy372;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych == 'l') goto yy375;
	goto yy236;
yy372:
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 239 "Lexer_re2c.cpp"
	{TOKEN(WHEN);}
#line 2910 "LexerTokenizer.cpp"
yy375:
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 235 "Lexer_re2c.cpp"
	{TOKEN(WHILE);}
#line 2920 "LexerTokenizer.cpp"
yy378:
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 172 "Lexer_re2c.cpp"
	{TOKEN(WCHAR);}
#line 2932 "LexerTokenizer.cpp"
yy382:
	yych = *++yycursor;
	if (yych == 'f') goto yy390;
	goto yy236;
yy383:
	++yycursor;
	if ((yych = *yycursor) <= '^') {
		if (yych <= '9') {
			if (yych >= '0') goto yy235;
		} else {
			if (yych <= '@') goto yy384;
			if (yych <= 'Z') goto yy235;
		}
	} else {
		if (yych <= 't') {
			if (yych != '`') goto yy235;
		} else {
			if (yych <= 'u') goto yy385;
			if (yych <= 'z') goto yy235;
		}
	}
yy384:
#line 237 "Lexer_re2c.cpp"
	{TOKEN(DO);}
#line 2957 "LexerTokenizer.cpp"
yy385:
	yych = *++yycursor;
	if (yych != 'b') goto yy236;
	yych = *++yycursor;
	if (yych != 'l') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 163 "Lexer_re2c.cpp"
	{TOKEN(DOUBLE);}
#line 2971 "LexerTokenizer.cpp"
yy390:
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 'u') goto yy236;
	yych = *++yycursor;
	if (yych != 'l') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 242 "Lexer_re2c.cpp"
	{TOKEN(DEFAULT);}
#line 2987 "LexerTokenizer.cpp"
yy396:
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	yych = *++yycursor;
	if (yych != 'd') goto yy236;
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 150 "Lexer_re2c.cpp"
	{TOKEN(PTRDIFF);}
#line 3005 "LexerTokenizer.cpp"
yy403:
	yych = *++yycursor;
	if (yych != 'p') goto yy236;
	yych = *++yycursor;
	if (yych != '_') goto yy236;
	yych = *++yycursor;
	if (yych != 'b') goto yy236;
	yych = *++yycursor;
	if (yych != 'u') goto yy236;
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 148 "Lexer_re2c.cpp"
	{TOKEN(JMP_BUF);}
#line 3023 "LexerTokenizer.cpp"
yy410:
	yych = *++yycursor;
	if (yych <= 'h') {
		if (yych == 'd') goto yy434;
		goto yy236;
	} else {
		if (yych <= 'i') goto yy432;
		if (yych == 'u') goto yy433;
		goto yy236;
	}
yy411:
	yych = *++yycursor;
	if (yych == '_') goto yy422;
	goto yy236;
yy412:
	yych = *++yycursor;
	if (yych <= 'm') goto yy236;
	if (yych <= 'n') goto yy413;
	if (yych <= 'o') goto yy414;
	goto yy236;
yy413:
	yych = *++yycursor;
	if (yych == 'g') goto yy417;
	goto yy236;
yy414:
	yych = *++yycursor;
	if (yych != 'p') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 233 "Lexer_re2c.cpp"
	{TOKEN(LOOP);}
#line 3057 "LexerTokenizer.cpp"
yy417:
	yych = *++yycursor;
	if (yych != 'j') goto yy236;
	yych = *++yycursor;
	if (yych != 'm') goto yy236;
	yych = *++yycursor;
	if (yych != 'p') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 226 "Lexer_re2c.cpp"
	{TOKEN(LONGJMP);}
#line 3071 "LexerTokenizer.cpp"
yy422:
	yych = *++yycursor;
	if (yych == 'i') goto yy423;
	if (yych == 'u') goto yy424;
	goto yy236;
yy423:
	yych = *++yycursor;
	if (yych == 'n') goto yy429;
	goto yy236;
yy424:
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 144 "Lexer_re2c.cpp"
	{TOKEN(LL_UINT);}
#line 3094 "LexerTokenizer.cpp"
yy429:
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 143 "Lexer_re2c.cpp"
	{TOKEN(LL_INT);}
#line 3104 "LexerTokenizer.cpp"
yy432:
	yych = *++yycursor;
	if (yych == 'n') goto yy445;
	goto yy236;
yy433:
	yych = *++yycursor;
	if (yych == 'i') goto yy441;
	goto yy236;
yy434:
	yych = *++yycursor;
	if (yych != 'o') goto yy236;
	yych = *++yycursor;
	if (yych != 'u') goto yy236;
	yych = *++yycursor;
	if (yych != 'b') goto yy236;
	yych = *++yycursor;
	if (yych != 'l') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 164 "Lexer_re2c.cpp"
	{TOKEN(L_DOUBLE);}
#line 3130 "LexerTokenizer.cpp"
yy441:
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 142 "Lexer_re2c.cpp"
	{TOKEN(L_UINT);}
#line 3142 "LexerTokenizer.cpp"
yy445:
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 141 "Lexer_re2c.cpp"
	{TOKEN(L_INT);}
#line 3152 "LexerTokenizer.cpp"
yy448:
	yych = *++yycursor;
	if (yych == '6') goto yy503;
	goto yy236;
yy449:
	yych = *++yycursor;
	if (yych == '2') goto yy501;
	goto yy236;
yy450:
	yych = *++yycursor;
	if (yych == '4') goto yy499;
	goto yy236;
yy451:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 157 "Lexer_re2c.cpp"
	{TOKEN(U8);}
#line 3172 "LexerTokenizer.cpp"
yy453:
	yych = *++yycursor;
	if (yych == 's') goto yy492;
	goto yy236;
yy454:
	yych = *++yycursor;
	if (yych == 'h') goto yy481;
	goto yy236;
yy455:
	yych = *++yycursor;
	if (yych == 'n') goto yy478;
	goto yy236;
yy456:
	yych = *++yycursor;
	if (yych == 'i') goto yy463;
	if (yych == 'l') goto yy464;
	goto yy236;
yy457:
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	yych = *++yycursor;
	if (yych != 'h') goto yy236;
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 173 "Lexer_re2c.cpp"
	{TOKEN(UWCHAR);}
#line 3205 "LexerTokenizer.cpp"
yy463:
	yych = *++yycursor;
	if (yych == 'o') goto yy475;
	goto yy236;
yy464:
	yych = *++yycursor;
	if (yych == 'e') goto yy465;
	if (yych == 'i') goto yy466;
	goto yy236;
yy465:
	yych = *++yycursor;
	if (yych == 's') goto yy472;
	goto yy236;
yy466:
	yych = *++yycursor;
	if (yych != 'k') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 'l') goto yy236;
	yych = *++yycursor;
	if (yych != 'y') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 217 "Lexer_re2c.cpp"
	{TOKEN(UNLIKELY);}
#line 3234 "LexerTokenizer.cpp"
yy472:
	yych = *++yycursor;
	if (yych != 's') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 216 "Lexer_re2c.cpp"
	{TOKEN(UNLESS);}
#line 3244 "LexerTokenizer.cpp"
yy475:
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 177 "Lexer_re2c.cpp"
	{TOKEN(UNION);}
#line 3254 "LexerTokenizer.cpp"
yy478:
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 138 "Lexer_re2c.cpp"
	{TOKEN(UINT);}
#line 3264 "LexerTokenizer.cpp"
yy481:
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	++yycursor;
	if ((yych = *yycursor) <= 'Z') {
		if (yych <= '/') goto yy484;
		if (yych <= '9') goto yy235;
		if (yych >= 'A') goto yy235;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy485;
		} else {
			if (yych <= '`') goto yy484;
			if (yych <= 'z') goto yy235;
		}
	}
yy484:
#line 167 "Lexer_re2c.cpp"
	{TOKEN(UCHAR);}
#line 3286 "LexerTokenizer.cpp"
yy485:
	yych = *++yycursor;
	if (yych == '1') goto yy486;
	if (yych == '3') goto yy487;
	goto yy236;
yy486:
	yych = *++yycursor;
	if (yych == '6') goto yy490;
	goto yy236;
yy487:
	yych = *++yycursor;
	if (yych != '2') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 171 "Lexer_re2c.cpp"
	{TOKEN(UCHAR);}
#line 3305 "LexerTokenizer.cpp"
yy490:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 169 "Lexer_re2c.cpp"
	{TOKEN(UCHAR);}
#line 3313 "LexerTokenizer.cpp"
yy492:
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'z') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != '_') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 147 "Lexer_re2c.cpp"
	{TOKEN(USIZE_T);}
#line 3331 "LexerTokenizer.cpp"
yy499:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 160 "Lexer_re2c.cpp"
	{TOKEN(U64);}
#line 3339 "LexerTokenizer.cpp"
yy501:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 159 "Lexer_re2c.cpp"
	{TOKEN(U32);}
#line 3347 "LexerTokenizer.cpp"
yy503:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 158 "Lexer_re2c.cpp"
	{TOKEN(U16);}
#line 3355 "LexerTokenizer.cpp"
yy505:
	yych = *++yycursor;
	if (yych == 'i') goto yy546;
	if (yych == 'u') goto yy547;
	goto yy236;
yy506:
	yych = *++yycursor;
	if (yych == 't') goto yy541;
	goto yy236;
yy507:
	yych = *++yycursor;
	if (yych == 'z') goto yy533;
	goto yy236;
yy508:
	yych = *++yycursor;
	if (yych == 'a') goto yy515;
	if (yych == 'r') goto yy516;
	goto yy236;
yy509:
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	yych = *++yycursor;
	if (yych != 'h') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 238 "Lexer_re2c.cpp"
	{TOKEN(SWITCH);}
#line 3389 "LexerTokenizer.cpp"
yy515:
	yych = *++yycursor;
	if (yych == 't') goto yy521;
	goto yy236;
yy516:
	yych = *++yycursor;
	if (yych != 'u') goto yy236;
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 176 "Lexer_re2c.cpp"
	{TOKEN(STRUCT);}
#line 3407 "LexerTokenizer.cpp"
yy521:
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	++yycursor;
	if ((yych = *yycursor) <= 'Z') {
		if (yych <= '/') goto yy524;
		if (yych <= '9') goto yy235;
		if (yych >= 'A') goto yy235;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy525;
		} else {
			if (yych <= '`') goto yy524;
			if (yych <= 'z') goto yy235;
		}
	}
yy524:
#line 187 "Lexer_re2c.cpp"
	{TOKEN(STATIC);}
#line 3429 "LexerTokenizer.cpp"
yy525:
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 's') goto yy236;
	yych = *++yycursor;
	if (yych != 's') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 135 "Lexer_re2c.cpp"
	{TOKEN(STATIC_ASSERT);}
#line 3449 "LexerTokenizer.cpp"
yy533:
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych == '_') goto yy535;
	if (yych == 'o') goto yy536;
	goto yy236;
yy535:
	yych = *++yycursor;
	if (yych == 't') goto yy539;
	goto yy236;
yy536:
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 180 "Lexer_re2c.cpp"
	{TOKEN(SIZEOF);}
#line 3470 "LexerTokenizer.cpp"
yy539:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 146 "Lexer_re2c.cpp"
	{TOKEN(SIZE_T);}
#line 3478 "LexerTokenizer.cpp"
yy541:
	yych = *++yycursor;
	if (yych != 'j') goto yy236;
	yych = *++yycursor;
	if (yych != 'm') goto yy236;
	yych = *++yycursor;
	if (yych != 'p') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 225 "Lexer_re2c.cpp"
	{TOKEN(SETJMP);}
#line 3492 "LexerTokenizer.cpp"
yy546:
	yych = *++yycursor;
	if (yych == 'n') goto yy552;
	goto yy236;
yy547:
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 140 "Lexer_re2c.cpp"
	{TOKEN(S_UINT);}
#line 3510 "LexerTokenizer.cpp"
yy552:
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 139 "Lexer_re2c.cpp"
	{TOKEN(S_INT);}
#line 3520 "LexerTokenizer.cpp"
yy555:
	yych = *++yycursor;
	if (yych == 's') goto yy584;
	goto yy236;
yy556:
	yych = *++yycursor;
	if (yych == 'a') goto yy574;
	goto yy236;
yy557:
	yych = *++yycursor;
	if (yych <= 'l') goto yy236;
	if (yych <= 'm') goto yy558;
	if (yych <= 'n') goto yy559;
	goto yy236;
yy558:
	yych = *++yycursor;
	if (yych == 'p') goto yy569;
	goto yy236;
yy559:
	yych = *++yycursor;
	if (yych <= 'r') goto yy236;
	if (yych <= 's') goto yy560;
	if (yych <= 't') goto yy561;
	goto yy236;
yy560:
	yych = *++yycursor;
	if (yych == 't') goto yy567;
	goto yy236;
yy561:
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	yych = *++yycursor;
	if (yych != 'u') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 222 "Lexer_re2c.cpp"
	{TOKEN(CONTINUE);}
#line 3564 "LexerTokenizer.cpp"
yy567:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 193 "Lexer_re2c.cpp"
	{TOKEN(CONST_QUALIFIER);}
#line 3572 "LexerTokenizer.cpp"
yy569:
	yych = *++yycursor;
	if (yych != 'l') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 'x') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 133 "Lexer_re2c.cpp"
	{TOKEN(COMPLEX);}
#line 3586 "LexerTokenizer.cpp"
yy574:
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	++yycursor;
	if ((yych = *yycursor) <= 'Z') {
		if (yych <= '/') goto yy576;
		if (yych <= '9') goto yy235;
		if (yych >= 'A') goto yy235;
	} else {
		if (yych <= '_') {
			if (yych >= '_') goto yy577;
		} else {
			if (yych <= '`') goto yy576;
			if (yych <= 'z') goto yy235;
		}
	}
yy576:
#line 166 "Lexer_re2c.cpp"
	{TOKEN(CHAR);}
#line 3606 "LexerTokenizer.cpp"
yy577:
	yych = *++yycursor;
	if (yych == '1') goto yy578;
	if (yych == '3') goto yy579;
	goto yy236;
yy578:
	yych = *++yycursor;
	if (yych == '6') goto yy582;
	goto yy236;
yy579:
	yych = *++yycursor;
	if (yych != '2') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 170 "Lexer_re2c.cpp"
	{TOKEN(CHAR);}
#line 3625 "LexerTokenizer.cpp"
yy582:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 168 "Lexer_re2c.cpp"
	{TOKEN(CHAR);}
#line 3633 "LexerTokenizer.cpp"
yy584:
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 240 "Lexer_re2c.cpp"
	{TOKEN(CASE);}
#line 3643 "LexerTokenizer.cpp"
yy587:
	yych = *++yycursor;
	if (yych == '_') goto yy599;
	goto yy236;
yy588:
	yych = *++yycursor;
	if (yych == 'i') goto yy589;
	if (yych == 'l') goto yy590;
	goto yy236;
yy589:
	yych = *++yycursor;
	if (yych == 'd') goto yy597;
	goto yy236;
yy590:
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'l') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 196 "Lexer_re2c.cpp"
	{TOKEN(VOLATILE_QUALIFIER);}
#line 3674 "LexerTokenizer.cpp"
yy597:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 131 "Lexer_re2c.cpp"
	{TOKEN(VOID);}
#line 3682 "LexerTokenizer.cpp"
yy599:
	yych = *++yycursor;
	switch (yych) {
	case 'a':	goto yy600;
	case 'c':	goto yy601;
	case 'e':	goto yy602;
	case 'l':	goto yy603;
	case 's':	goto yy604;
	default:	goto yy236;
	}
yy600:
	yych = *++yycursor;
	if (yych == 'r') goto yy621;
	goto yy236;
yy601:
	yych = *++yycursor;
	if (yych == 'o') goto yy617;
	goto yy236;
yy602:
	yych = *++yycursor;
	if (yych == 'n') goto yy614;
	goto yy236;
yy603:
	yych = *++yycursor;
	if (yych == 'i') goto yy610;
	goto yy236;
yy604:
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 229 "Lexer_re2c.cpp"
	{TOKEN(VA_START);}
#line 3724 "LexerTokenizer.cpp"
yy610:
	yych = *++yycursor;
	if (yych != 's') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 149 "Lexer_re2c.cpp"
	{TOKEN(VA_LIST);}
#line 3736 "LexerTokenizer.cpp"
yy614:
	yych = *++yycursor;
	if (yych != 'd') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 231 "Lexer_re2c.cpp"
	{TOKEN(VA_END);}
#line 3746 "LexerTokenizer.cpp"
yy617:
	yych = *++yycursor;
	if (yych != 'p') goto yy236;
	yych = *++yycursor;
	if (yych != 'y') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 230 "Lexer_re2c.cpp"
	{TOKEN(VA_COPY);}
#line 3758 "LexerTokenizer.cpp"
yy621:
	yych = *++yycursor;
	if (yych != 'g') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 228 "Lexer_re2c.cpp"
	{TOKEN(VA_ARG);}
#line 3768 "LexerTokenizer.cpp"
yy624:
	yych = *++yycursor;
	if (yych == 'f') goto yy658;
	if (yych == 'n') goto yy660;
	goto yy2;
yy625:
	yych = *++yycursor;
	if (yych == 'r') goto yy652;
	goto yy2;
yy626:
	yych = *++yycursor;
	if (yych == 'l') goto yy640;
	if (yych == 'r') goto yy641;
	goto yy2;
yy627:
	yych = *++yycursor;
	if (yych == 'n') goto yy635;
	goto yy2;
yy628:
	yych = *++yycursor;
	if (yych != 'e') goto yy2;
	yych = *++yycursor;
	if (yych != 'f') goto yy2;
	yych = *++yycursor;
	if (yych != 'i') goto yy2;
	yych = *++yycursor;
	if (yych != 'n') goto yy2;
	yych = *++yycursor;
	if (yych != 'e') goto yy2;
	++yycursor;
#line 206 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_DEFINE);}
#line 3801 "LexerTokenizer.cpp"
yy635:
	yych = *++yycursor;
	if (yych != 'd') goto yy2;
	yych = *++yycursor;
	if (yych != 'e') goto yy2;
	yych = *++yycursor;
	if (yych != 'f') goto yy2;
	++yycursor;
#line 207 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_UNDEF);}
#line 3812 "LexerTokenizer.cpp"
yy640:
	yych = *++yycursor;
	if (yych == 'i') goto yy647;
	if (yych == 's') goto yy646;
	goto yy2;
yy641:
	yych = *++yycursor;
	if (yych != 'r') goto yy2;
	yych = *++yycursor;
	if (yych != 'o') goto yy2;
	yych = *++yycursor;
	if (yych != 'r') goto yy2;
	++yycursor;
#line 208 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_ERROR);}
#line 3828 "LexerTokenizer.cpp"
yy646:
	yych = *++yycursor;
	if (yych == 'e') goto yy650;
	goto yy2;
yy647:
	yych = *++yycursor;
	if (yych != 'f') goto yy2;
	++yycursor;
#line 202 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_ELIF);}
#line 3839 "LexerTokenizer.cpp"
yy650:
	++yycursor;
#line 203 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_ELSE);}
#line 3844 "LexerTokenizer.cpp"
yy652:
	yych = *++yycursor;
	if (yych != 'a') goto yy2;
	yych = *++yycursor;
	if (yych != 'g') goto yy2;
	yych = *++yycursor;
	if (yych != 'm') goto yy2;
	yych = *++yycursor;
	if (yych != 'a') goto yy2;
	++yycursor;
#line 209 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_PRAGMA);}
#line 3857 "LexerTokenizer.cpp"
yy658:
	yyaccept = 9;
	yych = *(yymarker = ++yycursor);
	if (yych == 'd') goto yy668;
	if (yych == 'n') goto yy667;
yy659:
#line 201 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_IF);}
#line 3866 "LexerTokenizer.cpp"
yy660:
	yych = *++yycursor;
	if (yych != 'c') goto yy2;
	yych = *++yycursor;
	if (yych != 'l') goto yy2;
	yych = *++yycursor;
	if (yych != 'u') goto yy2;
	yych = *++yycursor;
	if (yych != 'd') goto yy2;
	yych = *++yycursor;
	if (yych != 'e') goto yy2;
	++yycursor;
#line 210 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_INCLUDE);}
#line 3881 "LexerTokenizer.cpp"
yy667:
	yych = *++yycursor;
	if (yych == 'd') goto yy672;
	goto yy2;
yy668:
	yych = *++yycursor;
	if (yych != 'e') goto yy2;
	yych = *++yycursor;
	if (yych != 'f') goto yy2;
	++yycursor;
#line 204 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_IFDEF);}
#line 3894 "LexerTokenizer.cpp"
yy672:
	yych = *++yycursor;
	if (yych != 'e') goto yy2;
	yych = *++yycursor;
	if (yych != 'f') goto yy2;
	++yycursor;
#line 205 "Lexer_re2c.cpp"
	{TOKEN(PRE_PROCESS_IFNDEF);}
#line 3903 "LexerTokenizer.cpp"
yy676:
	yych = *++yycursor;
	if (yych != '.') goto yy2;
	++yycursor;
#line 119 "Lexer_re2c.cpp"
	{TOKEN(ELLIPSIS);}
#line 3910 "LexerTokenizer.cpp"
yy679:
	++yycursor;
#line 112 "Lexer_re2c.cpp"
	{TOKEN(DEDUCE_EQUAL);}
#line 3915 "LexerTokenizer.cpp"
yy681:
	++yycursor;
#line 111 "Lexer_re2c.cpp"
	{TOKEN(QUESTION_EQUAL);}
#line 3920 "LexerTokenizer.cpp"
yy683:
	++yycursor;
#line 110 "Lexer_re2c.cpp"
	{TOKEN(AND_EQUAL);}
#line 3925 "LexerTokenizer.cpp"
yy685:
	++yycursor;
#line 109 "Lexer_re2c.cpp"
	{TOKEN(OR_EQUAL);}
#line 3930 "LexerTokenizer.cpp"
yy687:
	++yycursor;
#line 108 "Lexer_re2c.cpp"
	{TOKEN(XOR_EQUAL);}
#line 3935 "LexerTokenizer.cpp"
yy689:
	++yycursor;
#line 105 "Lexer_re2c.cpp"
	{TOKEN(DIV_EQUAL);}
#line 3940 "LexerTokenizer.cpp"
yy691:
	++yycursor;
#line 103 "Lexer_re2c.cpp"
	{TOKEN(TIMES_EQUAL);}
#line 3945 "LexerTokenizer.cpp"
yy693:
	++yycursor;
#line 114 "Lexer_re2c.cpp"
	{TOKEN(ARROW);}
#line 3950 "LexerTokenizer.cpp"
yy695:
	++yycursor;
#line 102 "Lexer_re2c.cpp"
	{TOKEN(MINUS_EQUAL);}
#line 3955 "LexerTokenizer.cpp"
yy697:
	++yycursor;
#line 97 "Lexer_re2c.cpp"
	{TOKEN(MINUS_MINUS);}
#line 3960 "LexerTokenizer.cpp"
yy699:
	++yycursor;
#line 101 "Lexer_re2c.cpp"
	{TOKEN(PLUS_EQUAL);}
#line 3965 "LexerTokenizer.cpp"
yy701:
	++yycursor;
#line 98 "Lexer_re2c.cpp"
	{TOKEN(PLUS_PLUS);}
#line 3970 "LexerTokenizer.cpp"
yy703:
	++yycursor;
#line 104 "Lexer_re2c.cpp"
	{TOKEN(MOD_EQUAL);}
#line 3975 "LexerTokenizer.cpp"
yy705:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy709;
#line 92 "Lexer_re2c.cpp"
	{TOKEN(L_SHIFT);}
#line 3981 "LexerTokenizer.cpp"
yy707:
	++yycursor;
#line 84 "Lexer_re2c.cpp"
	{TOKEN(LTE);}
#line 3986 "LexerTokenizer.cpp"
yy709:
	++yycursor;
#line 107 "Lexer_re2c.cpp"
	{TOKEN(L_SHIFT_EQUAL);}
#line 3991 "LexerTokenizer.cpp"
yy711:
	++yycursor;
	if ((yych = *yycursor) == '=') goto yy715;
#line 91 "Lexer_re2c.cpp"
	{TOKEN(R_SHIFT);}
#line 3997 "LexerTokenizer.cpp"
yy713:
	++yycursor;
#line 83 "Lexer_re2c.cpp"
	{TOKEN(GTE);}
#line 4002 "LexerTokenizer.cpp"
yy715:
	++yycursor;
#line 106 "Lexer_re2c.cpp"
	{TOKEN(R_SHIFT_EQUAL);}
#line 4007 "LexerTokenizer.cpp"
yy717:
	yych = *++yycursor;
	if (yych == 'f') goto yy733;
	goto yy236;
yy718:
	yych = *++yycursor;
	if (yych == '_') goto yy721;
	goto yy236;
yy719:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 78 "Lexer_re2c.cpp"
	{TOKEN(LOGIC_OR);}
#line 4023 "LexerTokenizer.cpp"
yy721:
	yych = *++yycursor;
	if (yych != 's') goto yy236;
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	yych = *++yycursor;
	if (yych != 'o') goto yy236;
	yych = *++yycursor;
	if (yych != 'p') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != '_') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 'x') goto yy236;
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 243 "Lexer_re2c.cpp"
	{TOKEN(ON_SCOPE_EXIT);}
#line 4051 "LexerTokenizer.cpp"
yy733:
	yych = *++yycursor;
	if (yych != 's') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	yych = *++yycursor;
	if (yych != 'o') goto yy236;
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 181 "Lexer_re2c.cpp"
	{TOKEN(OFFSETOF);}
#line 4069 "LexerTokenizer.cpp"
yy740:
	yych = *++yycursor;
	if (yych == 'i') goto yy750;
	goto yy236;
yy741:
	yych = *++yycursor;
	if (yych == 'd') goto yy748;
	goto yy236;
yy742:
	yych = *++yycursor;
	if (yych != 'o') goto yy236;
	yych = *++yycursor;
	if (yych != 'm') goto yy236;
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 194 "Lexer_re2c.cpp"
	{TOKEN(ATOMIC_QUALIFIER);}
#line 4093 "LexerTokenizer.cpp"
yy748:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 77 "Lexer_re2c.cpp"
	{TOKEN(LOGIC_AND);}
#line 4101 "LexerTokenizer.cpp"
yy750:
	yych = *++yycursor;
	if (yych != 'g') goto yy236;
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	yych = *++yycursor;
	if (yych == 'a') goto yy753;
	if (yych == 'o') goto yy754;
	goto yy236;
yy753:
	yych = *++yycursor;
	if (yych == 's') goto yy757;
	goto yy236;
yy754:
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 182 "Lexer_re2c.cpp"
	{TOKEN(ALIGNOF);}
#line 4124 "LexerTokenizer.cpp"
yy757:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 191 "Lexer_re2c.cpp"
	{TOKEN(ALIGNAS);}
#line 4132 "LexerTokenizer.cpp"
yy759:
	yych = *++yycursor;
	if (yych == 'r') goto yy762;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 76 "Lexer_re2c.cpp"
	{TOKEN(LOGIC_NOT);}
#line 4143 "LexerTokenizer.cpp"
yy762:
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	yych = *++yycursor;
	if (yych != 'u') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 197 "Lexer_re2c.cpp"
	{TOKEN(NORETURN_QUALIFIER);}
#line 4161 "LexerTokenizer.cpp"
yy769:
	yych = *++yycursor;
	if (yych == '6') goto yy812;
	goto yy236;
yy770:
	yych = *++yycursor;
	if (yych == '2') goto yy810;
	goto yy236;
yy771:
	yych = *++yycursor;
	if (yych == '4') goto yy808;
	goto yy236;
yy772:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 152 "Lexer_re2c.cpp"
	{TOKEN(I8);}
#line 4181 "LexerTokenizer.cpp"
yy774:
	++yycursor;
	if ((yych = *yycursor) <= '_') {
		if (yych <= '@') {
			if (yych <= '/') goto yy775;
			if (yych <= '9') goto yy235;
		} else {
			if (yych <= 'Z') goto yy235;
			if (yych >= '_') goto yy235;
		}
	} else {
		if (yych <= 'd') {
			if (yych <= '`') goto yy775;
			if (yych <= 'c') goto yy235;
			goto yy799;
		} else {
			if (yych == 'n') goto yy800;
			if (yych <= 'z') goto yy235;
		}
	}
yy775:
#line 215 "Lexer_re2c.cpp"
	{TOKEN(IF);}
#line 4205 "LexerTokenizer.cpp"
yy776:
	yych = *++yycursor;
	if (yych == 'a') goto yy791;
	goto yy236;
yy777:
	++yycursor;
	if ((yych = *yycursor) <= '_') {
		if (yych <= '@') {
			if (yych <= '/') goto yy778;
			if (yych <= '9') goto yy235;
		} else {
			if (yych <= 'Z') goto yy235;
			if (yych >= '_') goto yy235;
		}
	} else {
		if (yych <= 'l') {
			if (yych <= '`') goto yy778;
			if (yych <= 'k') goto yy235;
			goto yy786;
		} else {
			if (yych == 't') goto yy784;
			if (yych <= 'z') goto yy235;
		}
	}
yy778:
#line 79 "Lexer_re2c.cpp"
	{TOKEN(IN);}
#line 4233 "LexerTokenizer.cpp"
yy779:
	++yycursor;
	if ((yych = *yycursor) <= '^') {
		if (yych <= '9') {
			if (yych >= '0') goto yy235;
		} else {
			if (yych <= '@') goto yy780;
			if (yych <= 'Z') goto yy235;
		}
	} else {
		if (yych <= 'm') {
			if (yych != '`') goto yy235;
		} else {
			if (yych <= 'n') goto yy781;
			if (yych <= 'z') goto yy235;
		}
	}
yy780:
#line 74 "Lexer_re2c.cpp"
	{TOKEN(LOGIC_IS);}
#line 4254 "LexerTokenizer.cpp"
yy781:
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 75 "Lexer_re2c.cpp"
	{TOKEN(LOGIC_ISNT);}
#line 4264 "LexerTokenizer.cpp"
yy784:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 137 "Lexer_re2c.cpp"
	{TOKEN(INT);}
#line 4272 "LexerTokenizer.cpp"
yy786:
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 188 "Lexer_re2c.cpp"
	{TOKEN(INLINE);}
#line 4286 "LexerTokenizer.cpp"
yy791:
	yych = *++yycursor;
	if (yych != 'g') goto yy236;
	yych = *++yycursor;
	if (yych != 'i') goto yy236;
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 'r') goto yy236;
	yych = *++yycursor;
	if (yych != 'y') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 134 "Lexer_re2c.cpp"
	{TOKEN(IMAGINARY);}
#line 4306 "LexerTokenizer.cpp"
yy799:
	yych = *++yycursor;
	if (yych == 'e') goto yy805;
	goto yy236;
yy800:
	yych = *++yycursor;
	if (yych != 'd') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 213 "Lexer_re2c.cpp"
	{TOKEN(NO_AT_PRE_PROCESS_IFNDEF);}
#line 4324 "LexerTokenizer.cpp"
yy805:
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 212 "Lexer_re2c.cpp"
	{TOKEN(NO_AT_PRE_PROCESS_IFDEF);}
#line 4334 "LexerTokenizer.cpp"
yy808:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 155 "Lexer_re2c.cpp"
	{TOKEN(I64);}
#line 4342 "LexerTokenizer.cpp"
yy810:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 154 "Lexer_re2c.cpp"
	{TOKEN(I32);}
#line 4350 "LexerTokenizer.cpp"
yy812:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 153 "Lexer_re2c.cpp"
	{TOKEN(I16);}
#line 4358 "LexerTokenizer.cpp"
yy814:
	yych = *++yycursor;
	if (yych == 'l') goto yy827;
	goto yy236;
yy815:
	yych = *++yycursor;
	if (yych == 'o') goto yy823;
	goto yy236;
yy816:
	yych = *++yycursor;
	if (yych == 'r') goto yy821;
	goto yy236;
yy817:
	yych = *++yycursor;
	if (yych != 'o') goto yy236;
	yych = *++yycursor;
	if (yych != 'm') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 184 "Lexer_re2c.cpp"
	{TOKEN(FROM);}
#line 4382 "LexerTokenizer.cpp"
yy821:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 234 "Lexer_re2c.cpp"
	{TOKEN(FOR);}
#line 4390 "LexerTokenizer.cpp"
yy823:
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 't') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 162 "Lexer_re2c.cpp"
	{TOKEN(FLOAT);}
#line 4402 "LexerTokenizer.cpp"
yy827:
	yych = *++yycursor;
	if (yych != 's') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 72 "Lexer_re2c.cpp"
	{TOKEN(FALSE);}
#line 4414 "LexerTokenizer.cpp"
yy831:
	yych = *++yycursor;
	if (yych == 'e') goto yy846;
	if (yych == 'r') goto yy845;
	goto yy236;
yy832:
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 236 "Lexer_re2c.cpp"
	{TOKEN(TO);}
#line 4427 "LexerTokenizer.cpp"
yy834:
	yych = *++yycursor;
	if (yych == 'u') goto yy842;
	goto yy236;
yy835:
	yych = *++yycursor;
	if (yych != 'p') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 'd') goto yy236;
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	yych = *++yycursor;
	if (yych != 'f') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 175 "Lexer_re2c.cpp"
	{TOKEN(TYPEDEF);}
#line 4449 "LexerTokenizer.cpp"
yy842:
	yych = *++yycursor;
	if (yych != 'e') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 71 "Lexer_re2c.cpp"
	{TOKEN(TRUE);}
#line 4459 "LexerTokenizer.cpp"
yy845:
	yych = *++yycursor;
	if (yych == 'e') goto yy849;
	goto yy236;
yy846:
	yych = *++yycursor;
	if (yych != 'n') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 219 "Lexer_re2c.cpp"
	{TOKEN(THEN);}
#line 4473 "LexerTokenizer.cpp"
yy849:
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 'd') goto yy236;
	yych = *++yycursor;
	if (yych != '_') goto yy236;
	yych = *++yycursor;
	if (yych != 'l') goto yy236;
	yych = *++yycursor;
	if (yych != 'o') goto yy236;
	yych = *++yycursor;
	if (yych != 'c') goto yy236;
	yych = *++yycursor;
	if (yych != 'a') goto yy236;
	yych = *++yycursor;
	if (yych != 'l') goto yy236;
	++yycursor;
	if (yybm[0+(yych = *yycursor)] & 16) {
		goto yy235;
	}
#line 190 "Lexer_re2c.cpp"
	{TOKEN(THREAD_LOCAL);}
#line 4497 "LexerTokenizer.cpp"
yy859:
	++yycursor;
	yych = *yycursor;
yy860:
	if (yybm[0+yych] & 32) {
		goto yy859;
	}
	goto yy12;
yy861:
	++yycursor;
	yych = *yycursor;
yy862:
	if (yybm[0+yych] & 64) {
		goto yy861;
	}
	goto yy10;
yy863:
	yyaccept = 0;
	yymarker = ++yycursor;
	yych = *yycursor;
yy864:
	if (yybm[0+yych] & 128) {
		goto yy863;
	}
	if (yych <= 0xEF) {
		if (yych <= 0xC1) goto yy4;
		if (yych <= 0xDF) goto yy865;
		if (yych <= 0xE0) goto yy866;
		goto yy867;
	} else {
		if (yych <= 0xF0) goto yy868;
		if (yych <= 0xF3) goto yy869;
		if (yych <= 0xF4) goto yy870;
		goto yy4;
	}
yy865:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy863;
	goto yy2;
yy866:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x9F) goto yy2;
	if (yych <= 0xBF) goto yy865;
	goto yy2;
yy867:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy865;
	goto yy2;
yy868:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x8F) goto yy2;
	if (yych <= 0xBF) goto yy867;
	goto yy2;
yy869:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0xBF) goto yy867;
	goto yy2;
yy870:
	++yycursor;
	yych = *yycursor;
	if (yych <= 0x7F) goto yy2;
	if (yych <= 0x8F) goto yy867;
	goto yy2;
}
#line 329 "Lexer_re2c.cpp"

    }
}

} // namespace ppc
